apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "manager.fullname" . }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --port
            - {{ .Values.service.port | quote }}
            {{- if .Values.trustProxy }}
            - --trust-proxy
            {{- end }}
          env:
            - name: LAELIA_PG_URL
              valueFrom:
                secretKeyRef:
                  {{- if .Values.pg.existingSecret }}
                  name: {{ .Values.pg.existingSecret }}
                  {{- else }}
                  name: {{ include "manager.fullname" . }}
                  {{- end }}
                  key: LAELIA_PG_URL
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
