// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/command.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Ranxy/laelia/backend/generated-go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CommandServiceName is the fully-qualified name of the CommandService service.
	CommandServiceName = "laelia.v1.CommandService"
	// AgentCommandServiceName is the fully-qualified name of the AgentCommandService service.
	AgentCommandServiceName = "laelia.v1.AgentCommandService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CommandServiceSendCommandProcedure is the fully-qualified name of the CommandService's
	// SendCommand RPC.
	CommandServiceSendCommandProcedure = "/laelia.v1.CommandService/SendCommand"
	// CommandServiceListCommandsProcedure is the fully-qualified name of the CommandService's
	// ListCommands RPC.
	CommandServiceListCommandsProcedure = "/laelia.v1.CommandService/ListCommands"
	// CommandServiceGetCommandProcedure is the fully-qualified name of the CommandService's GetCommand
	// RPC.
	CommandServiceGetCommandProcedure = "/laelia.v1.CommandService/GetCommand"
	// CommandServiceCancelCommandProcedure is the fully-qualified name of the CommandService's
	// CancelCommand RPC.
	CommandServiceCancelCommandProcedure = "/laelia.v1.CommandService/CancelCommand"
	// CommandServiceWatchCommandProcedure is the fully-qualified name of the CommandService's
	// WatchCommand RPC.
	CommandServiceWatchCommandProcedure = "/laelia.v1.CommandService/WatchCommand"
	// AgentCommandServiceCommandChannelProcedure is the fully-qualified name of the
	// AgentCommandService's CommandChannel RPC.
	AgentCommandServiceCommandChannelProcedure = "/laelia.v1.AgentCommandService/CommandChannel"
)

// CommandServiceClient is a client for the laelia.v1.CommandService service.
type CommandServiceClient interface {
	SendCommand(context.Context, *connect.Request[v1.SendCommandRequest]) (*connect.Response[v1.Command], error)
	ListCommands(context.Context, *connect.Request[v1.ListCommandsRequest]) (*connect.Response[v1.ListCommandsResponse], error)
	GetCommand(context.Context, *connect.Request[v1.GetCommandRequest]) (*connect.Response[v1.Command], error)
	CancelCommand(context.Context, *connect.Request[v1.CancelCommandRequest]) (*connect.Response[v1.Command], error)
	WatchCommand(context.Context, *connect.Request[v1.WatchCommandRequest]) (*connect.ServerStreamForClient[v1.CommandOutput], error)
}

// NewCommandServiceClient constructs a client for the laelia.v1.CommandService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCommandServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CommandServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	commandServiceMethods := v1.File_v1_command_proto.Services().ByName("CommandService").Methods()
	return &commandServiceClient{
		sendCommand: connect.NewClient[v1.SendCommandRequest, v1.Command](
			httpClient,
			baseURL+CommandServiceSendCommandProcedure,
			connect.WithSchema(commandServiceMethods.ByName("SendCommand")),
			connect.WithClientOptions(opts...),
		),
		listCommands: connect.NewClient[v1.ListCommandsRequest, v1.ListCommandsResponse](
			httpClient,
			baseURL+CommandServiceListCommandsProcedure,
			connect.WithSchema(commandServiceMethods.ByName("ListCommands")),
			connect.WithClientOptions(opts...),
		),
		getCommand: connect.NewClient[v1.GetCommandRequest, v1.Command](
			httpClient,
			baseURL+CommandServiceGetCommandProcedure,
			connect.WithSchema(commandServiceMethods.ByName("GetCommand")),
			connect.WithClientOptions(opts...),
		),
		cancelCommand: connect.NewClient[v1.CancelCommandRequest, v1.Command](
			httpClient,
			baseURL+CommandServiceCancelCommandProcedure,
			connect.WithSchema(commandServiceMethods.ByName("CancelCommand")),
			connect.WithClientOptions(opts...),
		),
		watchCommand: connect.NewClient[v1.WatchCommandRequest, v1.CommandOutput](
			httpClient,
			baseURL+CommandServiceWatchCommandProcedure,
			connect.WithSchema(commandServiceMethods.ByName("WatchCommand")),
			connect.WithClientOptions(opts...),
		),
	}
}

// commandServiceClient implements CommandServiceClient.
type commandServiceClient struct {
	sendCommand   *connect.Client[v1.SendCommandRequest, v1.Command]
	listCommands  *connect.Client[v1.ListCommandsRequest, v1.ListCommandsResponse]
	getCommand    *connect.Client[v1.GetCommandRequest, v1.Command]
	cancelCommand *connect.Client[v1.CancelCommandRequest, v1.Command]
	watchCommand  *connect.Client[v1.WatchCommandRequest, v1.CommandOutput]
}

// SendCommand calls laelia.v1.CommandService.SendCommand.
func (c *commandServiceClient) SendCommand(ctx context.Context, req *connect.Request[v1.SendCommandRequest]) (*connect.Response[v1.Command], error) {
	return c.sendCommand.CallUnary(ctx, req)
}

// ListCommands calls laelia.v1.CommandService.ListCommands.
func (c *commandServiceClient) ListCommands(ctx context.Context, req *connect.Request[v1.ListCommandsRequest]) (*connect.Response[v1.ListCommandsResponse], error) {
	return c.listCommands.CallUnary(ctx, req)
}

// GetCommand calls laelia.v1.CommandService.GetCommand.
func (c *commandServiceClient) GetCommand(ctx context.Context, req *connect.Request[v1.GetCommandRequest]) (*connect.Response[v1.Command], error) {
	return c.getCommand.CallUnary(ctx, req)
}

// CancelCommand calls laelia.v1.CommandService.CancelCommand.
func (c *commandServiceClient) CancelCommand(ctx context.Context, req *connect.Request[v1.CancelCommandRequest]) (*connect.Response[v1.Command], error) {
	return c.cancelCommand.CallUnary(ctx, req)
}

// WatchCommand calls laelia.v1.CommandService.WatchCommand.
func (c *commandServiceClient) WatchCommand(ctx context.Context, req *connect.Request[v1.WatchCommandRequest]) (*connect.ServerStreamForClient[v1.CommandOutput], error) {
	return c.watchCommand.CallServerStream(ctx, req)
}

// CommandServiceHandler is an implementation of the laelia.v1.CommandService service.
type CommandServiceHandler interface {
	SendCommand(context.Context, *connect.Request[v1.SendCommandRequest]) (*connect.Response[v1.Command], error)
	ListCommands(context.Context, *connect.Request[v1.ListCommandsRequest]) (*connect.Response[v1.ListCommandsResponse], error)
	GetCommand(context.Context, *connect.Request[v1.GetCommandRequest]) (*connect.Response[v1.Command], error)
	CancelCommand(context.Context, *connect.Request[v1.CancelCommandRequest]) (*connect.Response[v1.Command], error)
	WatchCommand(context.Context, *connect.Request[v1.WatchCommandRequest], *connect.ServerStream[v1.CommandOutput]) error
}

// NewCommandServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCommandServiceHandler(svc CommandServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	commandServiceMethods := v1.File_v1_command_proto.Services().ByName("CommandService").Methods()
	commandServiceSendCommandHandler := connect.NewUnaryHandler(
		CommandServiceSendCommandProcedure,
		svc.SendCommand,
		connect.WithSchema(commandServiceMethods.ByName("SendCommand")),
		connect.WithHandlerOptions(opts...),
	)
	commandServiceListCommandsHandler := connect.NewUnaryHandler(
		CommandServiceListCommandsProcedure,
		svc.ListCommands,
		connect.WithSchema(commandServiceMethods.ByName("ListCommands")),
		connect.WithHandlerOptions(opts...),
	)
	commandServiceGetCommandHandler := connect.NewUnaryHandler(
		CommandServiceGetCommandProcedure,
		svc.GetCommand,
		connect.WithSchema(commandServiceMethods.ByName("GetCommand")),
		connect.WithHandlerOptions(opts...),
	)
	commandServiceCancelCommandHandler := connect.NewUnaryHandler(
		CommandServiceCancelCommandProcedure,
		svc.CancelCommand,
		connect.WithSchema(commandServiceMethods.ByName("CancelCommand")),
		connect.WithHandlerOptions(opts...),
	)
	commandServiceWatchCommandHandler := connect.NewServerStreamHandler(
		CommandServiceWatchCommandProcedure,
		svc.WatchCommand,
		connect.WithSchema(commandServiceMethods.ByName("WatchCommand")),
		connect.WithHandlerOptions(opts...),
	)
	return "/laelia.v1.CommandService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CommandServiceSendCommandProcedure:
			commandServiceSendCommandHandler.ServeHTTP(w, r)
		case CommandServiceListCommandsProcedure:
			commandServiceListCommandsHandler.ServeHTTP(w, r)
		case CommandServiceGetCommandProcedure:
			commandServiceGetCommandHandler.ServeHTTP(w, r)
		case CommandServiceCancelCommandProcedure:
			commandServiceCancelCommandHandler.ServeHTTP(w, r)
		case CommandServiceWatchCommandProcedure:
			commandServiceWatchCommandHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCommandServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCommandServiceHandler struct{}

func (UnimplementedCommandServiceHandler) SendCommand(context.Context, *connect.Request[v1.SendCommandRequest]) (*connect.Response[v1.Command], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.CommandService.SendCommand is not implemented"))
}

func (UnimplementedCommandServiceHandler) ListCommands(context.Context, *connect.Request[v1.ListCommandsRequest]) (*connect.Response[v1.ListCommandsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.CommandService.ListCommands is not implemented"))
}

func (UnimplementedCommandServiceHandler) GetCommand(context.Context, *connect.Request[v1.GetCommandRequest]) (*connect.Response[v1.Command], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.CommandService.GetCommand is not implemented"))
}

func (UnimplementedCommandServiceHandler) CancelCommand(context.Context, *connect.Request[v1.CancelCommandRequest]) (*connect.Response[v1.Command], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.CommandService.CancelCommand is not implemented"))
}

func (UnimplementedCommandServiceHandler) WatchCommand(context.Context, *connect.Request[v1.WatchCommandRequest], *connect.ServerStream[v1.CommandOutput]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.CommandService.WatchCommand is not implemented"))
}

// AgentCommandServiceClient is a client for the laelia.v1.AgentCommandService service.
type AgentCommandServiceClient interface {
	CommandChannel(context.Context) *connect.BidiStreamForClient[v1.AgentCommandMessage, v1.ManagerCommandMessage]
}

// NewAgentCommandServiceClient constructs a client for the laelia.v1.AgentCommandService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentCommandServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentCommandServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentCommandServiceMethods := v1.File_v1_command_proto.Services().ByName("AgentCommandService").Methods()
	return &agentCommandServiceClient{
		commandChannel: connect.NewClient[v1.AgentCommandMessage, v1.ManagerCommandMessage](
			httpClient,
			baseURL+AgentCommandServiceCommandChannelProcedure,
			connect.WithSchema(agentCommandServiceMethods.ByName("CommandChannel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentCommandServiceClient implements AgentCommandServiceClient.
type agentCommandServiceClient struct {
	commandChannel *connect.Client[v1.AgentCommandMessage, v1.ManagerCommandMessage]
}

// CommandChannel calls laelia.v1.AgentCommandService.CommandChannel.
func (c *agentCommandServiceClient) CommandChannel(ctx context.Context) *connect.BidiStreamForClient[v1.AgentCommandMessage, v1.ManagerCommandMessage] {
	return c.commandChannel.CallBidiStream(ctx)
}

// AgentCommandServiceHandler is an implementation of the laelia.v1.AgentCommandService service.
type AgentCommandServiceHandler interface {
	CommandChannel(context.Context, *connect.BidiStream[v1.AgentCommandMessage, v1.ManagerCommandMessage]) error
}

// NewAgentCommandServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentCommandServiceHandler(svc AgentCommandServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentCommandServiceMethods := v1.File_v1_command_proto.Services().ByName("AgentCommandService").Methods()
	agentCommandServiceCommandChannelHandler := connect.NewBidiStreamHandler(
		AgentCommandServiceCommandChannelProcedure,
		svc.CommandChannel,
		connect.WithSchema(agentCommandServiceMethods.ByName("CommandChannel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/laelia.v1.AgentCommandService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentCommandServiceCommandChannelProcedure:
			agentCommandServiceCommandChannelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentCommandServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentCommandServiceHandler struct{}

func (UnimplementedAgentCommandServiceHandler) CommandChannel(context.Context, *connect.BidiStream[v1.AgentCommandMessage, v1.ManagerCommandMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("laelia.v1.AgentCommandService.CommandChannel is not implemented"))
}
