// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/agent_team_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentTeamRole int32

const (
	AgentTeamRole_AGENT_TEAM_ROLE_UNSPECIFIED AgentTeamRole = 0
	AgentTeamRole_AGENT_TEAM_ROLE_LEADER      AgentTeamRole = 1
	AgentTeamRole_AGENT_TEAM_ROLE_MEMBER      AgentTeamRole = 2
)

// Enum value maps for AgentTeamRole.
var (
	AgentTeamRole_name = map[int32]string{
		0: "AGENT_TEAM_ROLE_UNSPECIFIED",
		1: "AGENT_TEAM_ROLE_LEADER",
		2: "AGENT_TEAM_ROLE_MEMBER",
	}
	AgentTeamRole_value = map[string]int32{
		"AGENT_TEAM_ROLE_UNSPECIFIED": 0,
		"AGENT_TEAM_ROLE_LEADER":      1,
		"AGENT_TEAM_ROLE_MEMBER":      2,
	}
)

func (x AgentTeamRole) Enum() *AgentTeamRole {
	p := new(AgentTeamRole)
	*p = x
	return p
}

func (x AgentTeamRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentTeamRole) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_team_service_proto_enumTypes[0].Descriptor()
}

func (AgentTeamRole) Type() protoreflect.EnumType {
	return &file_v1_agent_team_service_proto_enumTypes[0]
}

func (x AgentTeamRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentTeamRole.Descriptor instead.
func (AgentTeamRole) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{0}
}

// AgentTeam is a named collection of agents that work together on tasks. A
// team has exactly one leader and a team-level prompt that is injected into
// each member's context when the team is assigned to a task.
type AgentTeam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the team, in the form `agentTeams/{id}`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Longer description of the team.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Team-level prompt injected into every member's context when the team is
	// assigned to a task.
	TeamPrompt string `protobuf:"bytes,4,opt,name=team_prompt,json=teamPrompt,proto3" json:"team_prompt,omitempty"`
	// The leader agent resource name ("agents/{id}").
	LeaderAgent string `protobuf:"bytes,5,opt,name=leader_agent,json=leaderAgent,proto3" json:"leader_agent,omitempty"`
	// The team's members, including the leader.
	Members   []*AgentTeamMember     `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Output only. True when the caller may manage this team (the team owner or
	// a workspace admin).
	CanManage bool `protobuf:"varint,9,opt,name=can_manage,json=canManage,proto3" json:"can_manage,omitempty"`
	// The team owner's user resource name ("users/{id}").
	Owner         string `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTeam) Reset() {
	*x = AgentTeam{}
	mi := &file_v1_agent_team_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTeam) ProtoMessage() {}

func (x *AgentTeam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_team_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTeam.ProtoReflect.Descriptor instead.
func (*AgentTeam) Descriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{0}
}

func (x *AgentTeam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentTeam) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AgentTeam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentTeam) GetTeamPrompt() string {
	if x != nil {
		return x.TeamPrompt
	}
	return ""
}

func (x *AgentTeam) GetLeaderAgent() string {
	if x != nil {
		return x.LeaderAgent
	}
	return ""
}

func (x *AgentTeam) GetMembers() []*AgentTeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *AgentTeam) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentTeam) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AgentTeam) GetCanManage() bool {
	if x != nil {
		return x.CanManage
	}
	return false
}

func (x *AgentTeam) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type AgentTeamMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member agent resource name ("agents/{id}").
	Agent string `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// The member's role in the team.
	Role AgentTeamRole `protobuf:"varint,2,opt,name=role,proto3,enum=laelia.v1.AgentTeamRole" json:"role,omitempty"`
	// The member's responsibility in the team (free text).
	Responsibility string `protobuf:"bytes,3,opt,name=responsibility,proto3" json:"responsibility,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentTeamMember) Reset() {
	*x = AgentTeamMember{}
	mi := &file_v1_agent_team_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTeamMember) ProtoMessage() {}

func (x *AgentTeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_team_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTeamMember.ProtoReflect.Descriptor instead.
func (*AgentTeamMember) Descriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{1}
}

func (x *AgentTeamMember) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *AgentTeamMember) GetRole() AgentTeamRole {
	if x != nil {
		return x.Role
	}
	return AgentTeamRole_AGENT_TEAM_ROLE_UNSPECIFIED
}

func (x *AgentTeamMember) GetResponsibility() string {
	if x != nil {
		return x.Responsibility
	}
	return ""
}

type GetAgentTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team resource name, in the form `agentTeams/{id}`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentTeamRequest) Reset() {
	*x = GetAgentTeamRequest{}
	mi := &file_v1_agent_team_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentTeamRequest) ProtoMessage() {}

func (x *GetAgentTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_team_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentTeamRequest.ProtoReflect.Descriptor instead.
func (*GetAgentTeamRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAgentTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentTeamsRequest) Reset() {
	*x = ListAgentTeamsRequest{}
	mi := &file_v1_agent_team_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentTeamsRequest) ProtoMessage() {}

func (x *ListAgentTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_team_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentTeamsRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentTeamsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentTeamsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentTeams    []*AgentTeam           `protobuf:"bytes,1,rep,name=agent_teams,json=agentTeams,proto3" json:"agent_teams,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentTeamsResponse) Reset() {
	*x = ListAgentTeamsResponse{}
	mi := &file_v1_agent_team_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentTeamsResponse) ProtoMessage() {}

func (x *ListAgentTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_team_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentTeamsResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentTeamsResponse) GetAgentTeams() []*AgentTeam {
	if x != nil {
		return x.AgentTeams
	}
	return nil
}

func (x *ListAgentTeamsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateAgentTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team to create. The name field is ignored; title, leader_agent and
	// members are required.
	AgentTeam     *AgentTeam `protobuf:"bytes,1,opt,name=agent_team,json=agentTeam,proto3" json:"agent_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentTeamRequest) Reset() {
	*x = CreateAgentTeamRequest{}
	mi := &file_v1_agent_team_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentTeamRequest) ProtoMessage() {}

func (x *CreateAgentTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_team_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentTeamRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAgentTeamRequest) GetAgentTeam() *AgentTeam {
	if x != nil {
		return x.AgentTeam
	}
	return nil
}

type UpdateAgentTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team to update. The `name` field identifies the team.
	AgentTeam *AgentTeam `protobuf:"bytes,1,opt,name=agent_team,json=agentTeam,proto3" json:"agent_team,omitempty"`
	// The list of fields to update: "title", "description", "team_prompt",
	// "leader_agent", "members".
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentTeamRequest) Reset() {
	*x = UpdateAgentTeamRequest{}
	mi := &file_v1_agent_team_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentTeamRequest) ProtoMessage() {}

func (x *UpdateAgentTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_team_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentTeamRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentTeamRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAgentTeamRequest) GetAgentTeam() *AgentTeam {
	if x != nil {
		return x.AgentTeam
	}
	return nil
}

func (x *UpdateAgentTeamRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteAgentTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team resource name, in the form `agentTeams/{id}`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentTeamRequest) Reset() {
	*x = DeleteAgentTeamRequest{}
	mi := &file_v1_agent_team_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentTeamRequest) ProtoMessage() {}

func (x *DeleteAgentTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_team_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentTeamRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_team_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAgentTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_v1_agent_team_service_proto protoreflect.FileDescriptor

const file_v1_agent_team_service_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/agent_team_service.proto\x12\tlaelia.v1\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13v1/annotation.proto\"\xbd\x03\n" +
	"\tAgentTeam\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xe0A\b\xe0A\x02R\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vteam_prompt\x18\x04 \x01(\tR\n" +
	"teamPrompt\x12!\n" +
	"\fleader_agent\x18\x05 \x01(\tR\vleaderAgent\x124\n" +
	"\amembers\x18\x06 \x03(\v2\x1a.laelia.v1.AgentTeamMemberR\amembers\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\"\n" +
	"\n" +
	"can_manage\x18\t \x01(\bB\x03\xe0A\x03R\tcanManage\x12\x19\n" +
	"\x05owner\x18\n" +
	" \x01(\tB\x03\xe0A\x03R\x05owner:-\xeaA*\n" +
	"\x10laelia/AgentTeam\x12\x16agentTeams/{agentTeam}\"\x93\x01\n" +
	"\x0fAgentTeamMember\x12*\n" +
	"\x05agent\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\flaelia/AgentR\x05agent\x12,\n" +
	"\x04role\x18\x02 \x01(\x0e2\x18.laelia.v1.AgentTeamRoleR\x04role\x12&\n" +
	"\x0eresponsibility\x18\x03 \x01(\tR\x0eresponsibility\"C\n" +
	"\x13GetAgentTeamRequest\x12,\n" +
	"\x04name\x18\x01 \x01(\tB\x18\xe0A\x02\xfaA\x12\n" +
	"\x10laelia/AgentTeamR\x04name\"S\n" +
	"\x15ListAgentTeamsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"w\n" +
	"\x16ListAgentTeamsResponse\x125\n" +
	"\vagent_teams\x18\x01 \x03(\v2\x14.laelia.v1.AgentTeamR\n" +
	"agentTeams\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"R\n" +
	"\x16CreateAgentTeamRequest\x128\n" +
	"\n" +
	"agent_team\x18\x01 \x01(\v2\x14.laelia.v1.AgentTeamB\x03\xe0A\x02R\tagentTeam\"\x8f\x01\n" +
	"\x16UpdateAgentTeamRequest\x128\n" +
	"\n" +
	"agent_team\x18\x01 \x01(\v2\x14.laelia.v1.AgentTeamB\x03\xe0A\x02R\tagentTeam\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"F\n" +
	"\x16DeleteAgentTeamRequest\x12,\n" +
	"\x04name\x18\x01 \x01(\tB\x18\xe0A\x02\xfaA\x12\n" +
	"\x10laelia/AgentTeamR\x04name*h\n" +
	"\rAgentTeamRole\x12\x1f\n" +
	"\x1bAGENT_TEAM_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16AGENT_TEAM_ROLE_LEADER\x10\x01\x12\x1a\n" +
	"\x16AGENT_TEAM_ROLE_MEMBER\x10\x022\xc2\x04\n" +
	"\x10AgentTeamService\x12j\n" +
	"\fGetAgentTeam\x12\x1e.laelia.v1.GetAgentTeamRequest\x1a\x14.laelia.v1.AgentTeam\"$\xdaA\x04name\x8a\xea0\x15laelia.agentTeams.get\x90\xea0\x01\x12u\n" +
	"\x0eListAgentTeams\x12 .laelia.v1.ListAgentTeamsRequest\x1a!.laelia.v1.ListAgentTeamsResponse\"\x1e\x8a\xea0\x16laelia.agentTeams.list\x90\xea0\x01\x12}\n" +
	"\x0fCreateAgentTeam\x12!.laelia.v1.CreateAgentTeamRequest\x1a\x14.laelia.v1.AgentTeam\"1\xdaA\n" +
	"agent_team\x8a\xea0\x18laelia.agentTeams.create\x90\xea0\x01\x98\xea0\x01\x12m\n" +
	"\x0fUpdateAgentTeam\x12!.laelia.v1.UpdateAgentTeamRequest\x1a\x14.laelia.v1.AgentTeam\"!\xdaA\x16agent_team,update_mask\x90\xea0\x01\x98\xea0\x01\x12]\n" +
	"\x0fDeleteAgentTeam\x12!.laelia.v1.DeleteAgentTeamRequest\x1a\x16.google.protobuf.Empty\"\x0f\xdaA\x04name\x90\xea0\x01\x98\xea0\x01B1Z/github.com/Ranxy/laelia/backend/generated-go/v1b\x06proto3"

var (
	file_v1_agent_team_service_proto_rawDescOnce sync.Once
	file_v1_agent_team_service_proto_rawDescData []byte
)

func file_v1_agent_team_service_proto_rawDescGZIP() []byte {
	file_v1_agent_team_service_proto_rawDescOnce.Do(func() {
		file_v1_agent_team_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agent_team_service_proto_rawDesc), len(file_v1_agent_team_service_proto_rawDesc)))
	})
	return file_v1_agent_team_service_proto_rawDescData
}

var file_v1_agent_team_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_agent_team_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_agent_team_service_proto_goTypes = []any{
	(AgentTeamRole)(0),             // 0: laelia.v1.AgentTeamRole
	(*AgentTeam)(nil),              // 1: laelia.v1.AgentTeam
	(*AgentTeamMember)(nil),        // 2: laelia.v1.AgentTeamMember
	(*GetAgentTeamRequest)(nil),    // 3: laelia.v1.GetAgentTeamRequest
	(*ListAgentTeamsRequest)(nil),  // 4: laelia.v1.ListAgentTeamsRequest
	(*ListAgentTeamsResponse)(nil), // 5: laelia.v1.ListAgentTeamsResponse
	(*CreateAgentTeamRequest)(nil), // 6: laelia.v1.CreateAgentTeamRequest
	(*UpdateAgentTeamRequest)(nil), // 7: laelia.v1.UpdateAgentTeamRequest
	(*DeleteAgentTeamRequest)(nil), // 8: laelia.v1.DeleteAgentTeamRequest
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),  // 10: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_v1_agent_team_service_proto_depIdxs = []int32{
	2,  // 0: laelia.v1.AgentTeam.members:type_name -> laelia.v1.AgentTeamMember
	9,  // 1: laelia.v1.AgentTeam.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: laelia.v1.AgentTeam.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: laelia.v1.AgentTeamMember.role:type_name -> laelia.v1.AgentTeamRole
	1,  // 4: laelia.v1.ListAgentTeamsResponse.agent_teams:type_name -> laelia.v1.AgentTeam
	1,  // 5: laelia.v1.CreateAgentTeamRequest.agent_team:type_name -> laelia.v1.AgentTeam
	1,  // 6: laelia.v1.UpdateAgentTeamRequest.agent_team:type_name -> laelia.v1.AgentTeam
	10, // 7: laelia.v1.UpdateAgentTeamRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 8: laelia.v1.AgentTeamService.GetAgentTeam:input_type -> laelia.v1.GetAgentTeamRequest
	4,  // 9: laelia.v1.AgentTeamService.ListAgentTeams:input_type -> laelia.v1.ListAgentTeamsRequest
	6,  // 10: laelia.v1.AgentTeamService.CreateAgentTeam:input_type -> laelia.v1.CreateAgentTeamRequest
	7,  // 11: laelia.v1.AgentTeamService.UpdateAgentTeam:input_type -> laelia.v1.UpdateAgentTeamRequest
	8,  // 12: laelia.v1.AgentTeamService.DeleteAgentTeam:input_type -> laelia.v1.DeleteAgentTeamRequest
	1,  // 13: laelia.v1.AgentTeamService.GetAgentTeam:output_type -> laelia.v1.AgentTeam
	5,  // 14: laelia.v1.AgentTeamService.ListAgentTeams:output_type -> laelia.v1.ListAgentTeamsResponse
	1,  // 15: laelia.v1.AgentTeamService.CreateAgentTeam:output_type -> laelia.v1.AgentTeam
	1,  // 16: laelia.v1.AgentTeamService.UpdateAgentTeam:output_type -> laelia.v1.AgentTeam
	11, // 17: laelia.v1.AgentTeamService.DeleteAgentTeam:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_agent_team_service_proto_init() }
func file_v1_agent_team_service_proto_init() {
	if File_v1_agent_team_service_proto != nil {
		return
	}
	file_v1_annotation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agent_team_service_proto_rawDesc), len(file_v1_agent_team_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_agent_team_service_proto_goTypes,
		DependencyIndexes: file_v1_agent_team_service_proto_depIdxs,
		EnumInfos:         file_v1_agent_team_service_proto_enumTypes,
		MessageInfos:      file_v1_agent_team_service_proto_msgTypes,
	}.Build()
	File_v1_agent_team_service_proto = out.File
	file_v1_agent_team_service_proto_goTypes = nil
	file_v1_agent_team_service_proto_depIdxs = nil
}
