// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/setting.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingService_GetS3Config_FullMethodName       = "/laelia.v1.SettingService/GetS3Config"
	SettingService_UpdateS3Config_FullMethodName    = "/laelia.v1.SettingService/UpdateS3Config"
	SettingService_GetDebugConfig_FullMethodName    = "/laelia.v1.SettingService/GetDebugConfig"
	SettingService_UpdateDebugConfig_FullMethodName = "/laelia.v1.SettingService/UpdateDebugConfig"
)

// SettingServiceClient is the client API for SettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SettingService exposes workspace-level configuration. It is admin-only; the
// handlers enforce workspace admin membership and return
// connect.CodePermissionDenied otherwise. The S3 secret_key is masked on read;
// an update carrying a masked secret preserves the stored value.
type SettingServiceClient interface {
	GetS3Config(ctx context.Context, in *GetS3ConfigRequest, opts ...grpc.CallOption) (*GetS3ConfigResponse, error)
	UpdateS3Config(ctx context.Context, in *UpdateS3ConfigRequest, opts ...grpc.CallOption) (*UpdateS3ConfigResponse, error)
	GetDebugConfig(ctx context.Context, in *GetDebugConfigRequest, opts ...grpc.CallOption) (*GetDebugConfigResponse, error)
	UpdateDebugConfig(ctx context.Context, in *UpdateDebugConfigRequest, opts ...grpc.CallOption) (*UpdateDebugConfigResponse, error)
}

type settingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingServiceClient(cc grpc.ClientConnInterface) SettingServiceClient {
	return &settingServiceClient{cc}
}

func (c *settingServiceClient) GetS3Config(ctx context.Context, in *GetS3ConfigRequest, opts ...grpc.CallOption) (*GetS3ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetS3ConfigResponse)
	err := c.cc.Invoke(ctx, SettingService_GetS3Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) UpdateS3Config(ctx context.Context, in *UpdateS3ConfigRequest, opts ...grpc.CallOption) (*UpdateS3ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateS3ConfigResponse)
	err := c.cc.Invoke(ctx, SettingService_UpdateS3Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) GetDebugConfig(ctx context.Context, in *GetDebugConfigRequest, opts ...grpc.CallOption) (*GetDebugConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDebugConfigResponse)
	err := c.cc.Invoke(ctx, SettingService_GetDebugConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) UpdateDebugConfig(ctx context.Context, in *UpdateDebugConfigRequest, opts ...grpc.CallOption) (*UpdateDebugConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDebugConfigResponse)
	err := c.cc.Invoke(ctx, SettingService_UpdateDebugConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingServiceServer is the server API for SettingService service.
// All implementations must embed UnimplementedSettingServiceServer
// for forward compatibility.
//
// SettingService exposes workspace-level configuration. It is admin-only; the
// handlers enforce workspace admin membership and return
// connect.CodePermissionDenied otherwise. The S3 secret_key is masked on read;
// an update carrying a masked secret preserves the stored value.
type SettingServiceServer interface {
	GetS3Config(context.Context, *GetS3ConfigRequest) (*GetS3ConfigResponse, error)
	UpdateS3Config(context.Context, *UpdateS3ConfigRequest) (*UpdateS3ConfigResponse, error)
	GetDebugConfig(context.Context, *GetDebugConfigRequest) (*GetDebugConfigResponse, error)
	UpdateDebugConfig(context.Context, *UpdateDebugConfigRequest) (*UpdateDebugConfigResponse, error)
	mustEmbedUnimplementedSettingServiceServer()
}

// UnimplementedSettingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingServiceServer struct{}

func (UnimplementedSettingServiceServer) GetS3Config(context.Context, *GetS3ConfigRequest) (*GetS3ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetS3Config not implemented")
}
func (UnimplementedSettingServiceServer) UpdateS3Config(context.Context, *UpdateS3ConfigRequest) (*UpdateS3ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateS3Config not implemented")
}
func (UnimplementedSettingServiceServer) GetDebugConfig(context.Context, *GetDebugConfigRequest) (*GetDebugConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDebugConfig not implemented")
}
func (UnimplementedSettingServiceServer) UpdateDebugConfig(context.Context, *UpdateDebugConfigRequest) (*UpdateDebugConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDebugConfig not implemented")
}
func (UnimplementedSettingServiceServer) mustEmbedUnimplementedSettingServiceServer() {}
func (UnimplementedSettingServiceServer) testEmbeddedByValue()                        {}

// UnsafeSettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingServiceServer will
// result in compilation errors.
type UnsafeSettingServiceServer interface {
	mustEmbedUnimplementedSettingServiceServer()
}

func RegisterSettingServiceServer(s grpc.ServiceRegistrar, srv SettingServiceServer) {
	// If the following call panics, it indicates UnimplementedSettingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingService_ServiceDesc, srv)
}

func _SettingService_GetS3Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetS3ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).GetS3Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_GetS3Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).GetS3Config(ctx, req.(*GetS3ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_UpdateS3Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateS3ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).UpdateS3Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_UpdateS3Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).UpdateS3Config(ctx, req.(*UpdateS3ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_GetDebugConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDebugConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).GetDebugConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_GetDebugConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).GetDebugConfig(ctx, req.(*GetDebugConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_UpdateDebugConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDebugConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).UpdateDebugConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_UpdateDebugConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).UpdateDebugConfig(ctx, req.(*UpdateDebugConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingService_ServiceDesc is the grpc.ServiceDesc for SettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "laelia.v1.SettingService",
	HandlerType: (*SettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetS3Config",
			Handler:    _SettingService_GetS3Config_Handler,
		},
		{
			MethodName: "UpdateS3Config",
			Handler:    _SettingService_UpdateS3Config_Handler,
		},
		{
			MethodName: "GetDebugConfig",
			Handler:    _SettingService_GetDebugConfig_Handler,
		},
		{
			MethodName: "UpdateDebugConfig",
			Handler:    _SettingService_UpdateDebugConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/setting.proto",
}
