// @generated by protoc-gen-es v2.12.0
// @generated from file v1/agent.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import type { State } from "./common_pb";

/**
 * Describes the file v1/agent.proto.
 */
export declare const file_v1_agent: GenFile;

/**
 * @generated from message laelia.v1.CreateAgentRequest
 */
export declare type CreateAgentRequest = Message<"laelia.v1.CreateAgentRequest"> & {
  /**
   * @generated from field: laelia.v1.Agent agent = 1;
   */
  agent?: Agent | undefined;
};

/**
 * Describes the message laelia.v1.CreateAgentRequest.
 * Use `create(CreateAgentRequestSchema)` to create a new message.
 */
export declare const CreateAgentRequestSchema: GenMessage<CreateAgentRequest>;

/**
 * @generated from message laelia.v1.CreateAgentResponse
 */
export declare type CreateAgentResponse = Message<"laelia.v1.CreateAgentResponse"> & {
  /**
   * @generated from field: laelia.v1.Agent agent = 1;
   */
  agent?: Agent | undefined;

  /**
   * 7-day validity, reusable until rotated/revoked
   *
   * @generated from field: string bootstrap_token = 2;
   */
  bootstrapToken: string;
};

/**
 * Describes the message laelia.v1.CreateAgentResponse.
 * Use `create(CreateAgentResponseSchema)` to create a new message.
 */
export declare const CreateAgentResponseSchema: GenMessage<CreateAgentResponse>;

/**
 * @generated from message laelia.v1.RotateAgentTokenRequest
 */
export declare type RotateAgentTokenRequest = Message<"laelia.v1.RotateAgentTokenRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * audit purpose
   *
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.RotateAgentTokenRequest.
 * Use `create(RotateAgentTokenRequestSchema)` to create a new message.
 */
export declare const RotateAgentTokenRequestSchema: GenMessage<RotateAgentTokenRequest>;

/**
 * @generated from message laelia.v1.RotateAgentTokenResponse
 */
export declare type RotateAgentTokenResponse = Message<"laelia.v1.RotateAgentTokenResponse"> & {
  /**
   * new bootstrap token
   *
   * @generated from field: string bootstrap_token = 1;
   */
  bootstrapToken: string;
};

/**
 * Describes the message laelia.v1.RotateAgentTokenResponse.
 * Use `create(RotateAgentTokenResponseSchema)` to create a new message.
 */
export declare const RotateAgentTokenResponseSchema: GenMessage<RotateAgentTokenResponse>;

/**
 * @generated from message laelia.v1.RevokeAgentTokenRequest
 */
export declare type RevokeAgentTokenRequest = Message<"laelia.v1.RevokeAgentTokenRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.RevokeAgentTokenRequest.
 * Use `create(RevokeAgentTokenRequestSchema)` to create a new message.
 */
export declare const RevokeAgentTokenRequestSchema: GenMessage<RevokeAgentTokenRequest>;

/**
 * @generated from message laelia.v1.RevokeAgentTokenResponse
 */
export declare type RevokeAgentTokenResponse = Message<"laelia.v1.RevokeAgentTokenResponse"> & {
};

/**
 * Describes the message laelia.v1.RevokeAgentTokenResponse.
 * Use `create(RevokeAgentTokenResponseSchema)` to create a new message.
 */
export declare const RevokeAgentTokenResponseSchema: GenMessage<RevokeAgentTokenResponse>;

/**
 * @generated from message laelia.v1.ForceDisconnectAgentRequest
 */
export declare type ForceDisconnectAgentRequest = Message<"laelia.v1.ForceDisconnectAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.ForceDisconnectAgentRequest.
 * Use `create(ForceDisconnectAgentRequestSchema)` to create a new message.
 */
export declare const ForceDisconnectAgentRequestSchema: GenMessage<ForceDisconnectAgentRequest>;

/**
 * @generated from message laelia.v1.ListAgentSessionsRequest
 */
export declare type ListAgentSessionsRequest = Message<"laelia.v1.ListAgentSessionsRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * default: only active sessions
   *
   * @generated from field: bool include_terminated = 4;
   */
  includeTerminated: boolean;
};

/**
 * Describes the message laelia.v1.ListAgentSessionsRequest.
 * Use `create(ListAgentSessionsRequestSchema)` to create a new message.
 */
export declare const ListAgentSessionsRequestSchema: GenMessage<ListAgentSessionsRequest>;

/**
 * @generated from message laelia.v1.ListAgentSessionsResponse
 */
export declare type ListAgentSessionsResponse = Message<"laelia.v1.ListAgentSessionsResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.AgentSession sessions = 1;
   */
  sessions: AgentSession[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message laelia.v1.ListAgentSessionsResponse.
 * Use `create(ListAgentSessionsResponseSchema)` to create a new message.
 */
export declare const ListAgentSessionsResponseSchema: GenMessage<ListAgentSessionsResponse>;

/**
 * @generated from message laelia.v1.AgentSession
 */
export declare type AgentSession = Message<"laelia.v1.AgentSession"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string agent_name = 2;
   */
  agentName: string;

  /**
   * @generated from field: string source_ip = 3;
   */
  sourceIp: string;

  /**
   * @generated from field: string agent_version = 4;
   */
  agentVersion: string;

  /**
   * @generated from field: string fingerprint = 5;
   */
  fingerprint: string;

  /**
   * @generated from field: google.protobuf.Timestamp connected_at = 6;
   */
  connectedAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp last_heartbeat_at = 7;
   */
  lastHeartbeatAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp disconnected_at = 8;
   */
  disconnectedAt?: Timestamp | undefined;

  /**
   * @generated from field: string disconnect_reason = 9;
   */
  disconnectReason: string;

  /**
   * @generated from field: laelia.v1.AgentStatus.ConnectionState state = 10;
   */
  state: AgentStatus_ConnectionState;
};

/**
 * Describes the message laelia.v1.AgentSession.
 * Use `create(AgentSessionSchema)` to create a new message.
 */
export declare const AgentSessionSchema: GenMessage<AgentSession>;

/**
 * @generated from message laelia.v1.ConnectAgentRequest
 */
export declare type ConnectAgentRequest = Message<"laelia.v1.ConnectAgentRequest"> & {
  /**
   * first connection or after refresh failure
   *
   * @generated from field: string bootstrap_token = 1;
   */
  bootstrapToken: string;

  /**
   * @generated from field: laelia.v1.AgentInfo info = 2;
   */
  info?: AgentInfo | undefined;

  /**
   * client-generated connection fingerprint (hostname:os:arch)
   *
   * @generated from field: string fingerprint = 3;
   */
  fingerprint: string;
};

/**
 * Describes the message laelia.v1.ConnectAgentRequest.
 * Use `create(ConnectAgentRequestSchema)` to create a new message.
 */
export declare const ConnectAgentRequestSchema: GenMessage<ConnectAgentRequest>;

/**
 * @generated from message laelia.v1.ConnectAgentResponse
 */
export declare type ConnectAgentResponse = Message<"laelia.v1.ConnectAgentResponse"> & {
  /**
   * 15-minute validity
   *
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * 24-hour validity, single-use rotation
   *
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * session identifier
   *
   * @generated from field: string session_id = 3;
   */
  sessionId: string;

  /**
   * server-signed nonce for next heartbeat
   *
   * @generated from field: string next_nonce = 4;
   */
  nextNonce: string;

  /**
   * @generated from field: google.protobuf.Timestamp access_token_expires_at = 5;
   */
  accessTokenExpiresAt?: Timestamp | undefined;

  /**
   * @generated from field: laelia.v1.AgentStatus initial_status = 6;
   */
  initialStatus?: AgentStatus | undefined;
};

/**
 * Describes the message laelia.v1.ConnectAgentResponse.
 * Use `create(ConnectAgentResponseSchema)` to create a new message.
 */
export declare const ConnectAgentResponseSchema: GenMessage<ConnectAgentResponse>;

/**
 * @generated from message laelia.v1.AgentHeartbeatRequest
 */
export declare type AgentHeartbeatRequest = Message<"laelia.v1.AgentHeartbeatRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * nonce from previous response (replay protection)
   *
   * @generated from field: string previous_nonce = 2;
   */
  previousNonce: string;

  /**
   * optional agent metrics
   *
   * @generated from field: laelia.v1.AgentMetrics metrics = 3;
   */
  metrics?: AgentMetrics | undefined;
};

/**
 * Describes the message laelia.v1.AgentHeartbeatRequest.
 * Use `create(AgentHeartbeatRequestSchema)` to create a new message.
 */
export declare const AgentHeartbeatRequestSchema: GenMessage<AgentHeartbeatRequest>;

/**
 * @generated from message laelia.v1.AgentHeartbeatResponse
 */
export declare type AgentHeartbeatResponse = Message<"laelia.v1.AgentHeartbeatResponse"> & {
  /**
   * nonce for next request
   *
   * @generated from field: string next_nonce = 1;
   */
  nextNonce: string;

  /**
   * expected next heartbeat time
   *
   * @generated from field: google.protobuf.Timestamp next_heartbeat_at = 2;
   */
  nextHeartbeatAt?: Timestamp | undefined;

  /**
   * new access token (only if expiring soon)
   *
   * @generated from field: string access_token = 3;
   */
  accessToken: string;

  /**
   * @generated from field: google.protobuf.Timestamp access_token_expires_at = 4;
   */
  accessTokenExpiresAt?: Timestamp | undefined;
};

/**
 * Describes the message laelia.v1.AgentHeartbeatResponse.
 * Use `create(AgentHeartbeatResponseSchema)` to create a new message.
 */
export declare const AgentHeartbeatResponseSchema: GenMessage<AgentHeartbeatResponse>;

/**
 * @generated from message laelia.v1.AgentDisconnectRequest
 */
export declare type AgentDisconnectRequest = Message<"laelia.v1.AgentDisconnectRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * "shutdown", "upgrade" etc.
   *
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.AgentDisconnectRequest.
 * Use `create(AgentDisconnectRequestSchema)` to create a new message.
 */
export declare const AgentDisconnectRequestSchema: GenMessage<AgentDisconnectRequest>;

/**
 * @generated from message laelia.v1.RefreshAgentTokenRequest
 */
export declare type RefreshAgentTokenRequest = Message<"laelia.v1.RefreshAgentTokenRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  /**
   * verify connection fingerprint
   *
   * @generated from field: string fingerprint = 2;
   */
  fingerprint: string;
};

/**
 * Describes the message laelia.v1.RefreshAgentTokenRequest.
 * Use `create(RefreshAgentTokenRequestSchema)` to create a new message.
 */
export declare const RefreshAgentTokenRequestSchema: GenMessage<RefreshAgentTokenRequest>;

/**
 * @generated from message laelia.v1.RefreshAgentTokenResponse
 */
export declare type RefreshAgentTokenResponse = Message<"laelia.v1.RefreshAgentTokenResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * new refresh token (rotation)
   *
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: google.protobuf.Timestamp access_token_expires_at = 3;
   */
  accessTokenExpiresAt?: Timestamp | undefined;
};

/**
 * Describes the message laelia.v1.RefreshAgentTokenResponse.
 * Use `create(RefreshAgentTokenResponseSchema)` to create a new message.
 */
export declare const RefreshAgentTokenResponseSchema: GenMessage<RefreshAgentTokenResponse>;

/**
 * @generated from message laelia.v1.ListAgentsRequest
 */
export declare type ListAgentsRequest = Message<"laelia.v1.ListAgentsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: bool show_deleted = 3;
   */
  showDeleted: boolean;
};

/**
 * Describes the message laelia.v1.ListAgentsRequest.
 * Use `create(ListAgentsRequestSchema)` to create a new message.
 */
export declare const ListAgentsRequestSchema: GenMessage<ListAgentsRequest>;

/**
 * @generated from message laelia.v1.ListAgentsResponse
 */
export declare type ListAgentsResponse = Message<"laelia.v1.ListAgentsResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.Agent agents = 1;
   */
  agents: Agent[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message laelia.v1.ListAgentsResponse.
 * Use `create(ListAgentsResponseSchema)` to create a new message.
 */
export declare const ListAgentsResponseSchema: GenMessage<ListAgentsResponse>;

/**
 * @generated from message laelia.v1.GetAgentRequest
 */
export declare type GetAgentRequest = Message<"laelia.v1.GetAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.GetAgentRequest.
 * Use `create(GetAgentRequestSchema)` to create a new message.
 */
export declare const GetAgentRequestSchema: GenMessage<GetAgentRequest>;

/**
 * @generated from message laelia.v1.DeleteAgentRequest
 */
export declare type DeleteAgentRequest = Message<"laelia.v1.DeleteAgentRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.DeleteAgentRequest.
 * Use `create(DeleteAgentRequestSchema)` to create a new message.
 */
export declare const DeleteAgentRequestSchema: GenMessage<DeleteAgentRequest>;

/**
 * @generated from message laelia.v1.HelloRequest
 */
export declare type HelloRequest = Message<"laelia.v1.HelloRequest"> & {
};

/**
 * Describes the message laelia.v1.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export declare const HelloRequestSchema: GenMessage<HelloRequest>;

/**
 * @generated from message laelia.v1.HelloResponse
 */
export declare type HelloResponse = Message<"laelia.v1.HelloResponse"> & {
  /**
   * @generated from field: int64 current_time = 1;
   */
  currentTime: bigint;

  /**
   * @generated from field: string server_version = 2;
   */
  serverVersion: string;
};

/**
 * Describes the message laelia.v1.HelloResponse.
 * Use `create(HelloResponseSchema)` to create a new message.
 */
export declare const HelloResponseSchema: GenMessage<HelloResponse>;

/**
 * @generated from message laelia.v1.Agent
 */
export declare type Agent = Message<"laelia.v1.Agent"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: laelia.v1.State state = 2;
   */
  state: State;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: laelia.v1.AgentInfo info = 5;
   */
  info?: AgentInfo | undefined;

  /**
   * @generated from field: laelia.v1.AgentStatus status = 6;
   */
  status?: AgentStatus | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: map<string, string> labels = 8;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: google.protobuf.Timestamp last_token_rotated_at = 9;
   */
  lastTokenRotatedAt?: Timestamp | undefined;

  /**
   * @generated from field: int32 token_version = 10;
   */
  tokenVersion: number;
};

/**
 * Describes the message laelia.v1.Agent.
 * Use `create(AgentSchema)` to create a new message.
 */
export declare const AgentSchema: GenMessage<Agent>;

/**
 * @generated from message laelia.v1.AgentInfo
 */
export declare type AgentInfo = Message<"laelia.v1.AgentInfo"> & {
  /**
   * @generated from field: string agent_type = 1;
   */
  agentType: string;

  /**
   * @generated from field: string hostname = 2;
   */
  hostname: string;

  /**
   * @generated from field: string os = 3;
   */
  os: string;

  /**
   * @generated from field: string arch = 4;
   */
  arch: string;

  /**
   * @generated from field: string ip = 5;
   */
  ip: string;

  /**
   * @generated from field: string version = 6;
   */
  version: string;

  /**
   * @generated from field: map<string, string> labels = 7;
   */
  labels: { [key: string]: string };
};

/**
 * Describes the message laelia.v1.AgentInfo.
 * Use `create(AgentInfoSchema)` to create a new message.
 */
export declare const AgentInfoSchema: GenMessage<AgentInfo>;

/**
 * @generated from message laelia.v1.AgentStatus
 */
export declare type AgentStatus = Message<"laelia.v1.AgentStatus"> & {
  /**
   * @generated from field: laelia.v1.AgentStatus.ConnectionState state = 1;
   */
  state: AgentStatus_ConnectionState;

  /**
   * @generated from field: google.protobuf.Timestamp last_heartbeat_time = 2;
   */
  lastHeartbeatTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp connected_time = 3;
   */
  connectedTime?: Timestamp | undefined;

  /**
   * @generated from field: string error_message = 4;
   */
  errorMessage: string;

  /**
   * current active session ID
   *
   * @generated from field: string active_session_id = 5;
   */
  activeSessionId: string;
};

/**
 * Describes the message laelia.v1.AgentStatus.
 * Use `create(AgentStatusSchema)` to create a new message.
 */
export declare const AgentStatusSchema: GenMessage<AgentStatus>;

/**
 * @generated from enum laelia.v1.AgentStatus.ConnectionState
 */
export enum AgentStatus_ConnectionState {
  /**
   * @generated from enum value: CONNECTION_STATE_UNSPECIFIED = 0;
   */
  CONNECTION_STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ONLINE = 1;
   */
  ONLINE = 1,

  /**
   * @generated from enum value: OFFLINE = 2;
   */
  OFFLINE = 2,

  /**
   * @generated from enum value: ERROR = 3;
   */
  ERROR = 3,

  /**
   * evicted by a new connection
   *
   * @generated from enum value: KICKED = 4;
   */
  KICKED = 4,
}

/**
 * Describes the enum laelia.v1.AgentStatus.ConnectionState.
 */
export declare const AgentStatus_ConnectionStateSchema: GenEnum<AgentStatus_ConnectionState>;

/**
 * @generated from message laelia.v1.AgentMetrics
 */
export declare type AgentMetrics = Message<"laelia.v1.AgentMetrics"> & {
  /**
   * @generated from field: double cpu_percent = 1;
   */
  cpuPercent: number;

  /**
   * @generated from field: uint64 memory_used_bytes = 2;
   */
  memoryUsedBytes: bigint;

  /**
   * @generated from field: uint64 memory_total_bytes = 3;
   */
  memoryTotalBytes: bigint;

  /**
   * @generated from field: uint64 disk_used_bytes = 4;
   */
  diskUsedBytes: bigint;

  /**
   * @generated from field: uint64 disk_total_bytes = 5;
   */
  diskTotalBytes: bigint;

  /**
   * @generated from field: uint32 uptime_seconds = 6;
   */
  uptimeSeconds: number;

  /**
   * @generated from field: uint32 goroutine_count = 7;
   */
  goroutineCount: number;
};

/**
 * Describes the message laelia.v1.AgentMetrics.
 * Use `create(AgentMetricsSchema)` to create a new message.
 */
export declare const AgentMetricsSchema: GenMessage<AgentMetrics>;

/**
 * ========== Management APIs (IAM auth, admin only) ==========
 *
 * @generated from service laelia.v1.AgentService
 */
export declare const AgentService: GenService<{
  /**
   * @generated from rpc laelia.v1.AgentService.CreateAgent
   */
  createAgent: {
    methodKind: "unary";
    input: typeof CreateAgentRequestSchema;
    output: typeof CreateAgentResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.AgentService.ListAgents
   */
  listAgents: {
    methodKind: "unary";
    input: typeof ListAgentsRequestSchema;
    output: typeof ListAgentsResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.AgentService.GetAgent
   */
  getAgent: {
    methodKind: "unary";
    input: typeof GetAgentRequestSchema;
    output: typeof AgentSchema;
  },
  /**
   * @generated from rpc laelia.v1.AgentService.DeleteAgent
   */
  deleteAgent: {
    methodKind: "unary";
    input: typeof DeleteAgentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Token rotation: generate a new bootstrap token, old token invalid after grace period
   *
   * @generated from rpc laelia.v1.AgentService.RotateAgentToken
   */
  rotateAgentToken: {
    methodKind: "unary";
    input: typeof RotateAgentTokenRequestSchema;
    output: typeof RotateAgentTokenResponseSchema;
  },
  /**
   * Token revocation: revoke all tokens for the agent
   *
   * @generated from rpc laelia.v1.AgentService.RevokeAgentToken
   */
  revokeAgentToken: {
    methodKind: "unary";
    input: typeof RevokeAgentTokenRequestSchema;
    output: typeof RevokeAgentTokenResponseSchema;
  },
  /**
   * Admin force disconnects an agent connection
   *
   * @generated from rpc laelia.v1.AgentService.ForceDisconnectAgent
   */
  forceDisconnectAgent: {
    methodKind: "unary";
    input: typeof ForceDisconnectAgentRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * List agent sessions
   *
   * @generated from rpc laelia.v1.AgentService.ListAgentSessions
   */
  listAgentSessions: {
    methodKind: "unary";
    input: typeof ListAgentSessionsRequestSchema;
    output: typeof ListAgentSessionsResponseSchema;
  },
  /**
   * Agent initial connection using bootstrap token
   *
   * @generated from rpc laelia.v1.AgentService.ConnectAgent
   */
  connectAgent: {
    methodKind: "unary";
    input: typeof ConnectAgentRequestSchema;
    output: typeof ConnectAgentResponseSchema;
  },
  /**
   * Agent heartbeat
   *
   * @generated from rpc laelia.v1.AgentService.AgentHeartbeat
   */
  agentHeartbeat: {
    methodKind: "unary";
    input: typeof AgentHeartbeatRequestSchema;
    output: typeof AgentHeartbeatResponseSchema;
  },
  /**
   * Agent graceful disconnect
   *
   * @generated from rpc laelia.v1.AgentService.AgentDisconnect
   */
  agentDisconnect: {
    methodKind: "unary";
    input: typeof AgentDisconnectRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Agent refreshes access token
   *
   * @generated from rpc laelia.v1.AgentService.RefreshAgentToken
   */
  refreshAgentToken: {
    methodKind: "unary";
    input: typeof RefreshAgentTokenRequestSchema;
    output: typeof RefreshAgentTokenResponseSchema;
  },
  /**
   * Health check (no auth required)
   *
   * @generated from rpc laelia.v1.AgentService.Hello
   */
  hello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloResponseSchema;
  },
}>;

