// @generated by protoc-gen-es v2.12.0
// @generated from file v1/api_provider_service.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";
import type { PiModel } from "./agent_pb";

/**
 * Describes the file v1/api_provider_service.proto.
 */
export declare const file_v1_api_provider_service: GenFile;

/**
 * ApiProvider is a named global LLM API provider (e.g. "DeepSeek"). A provider
 * bundles a set of (api_key, model) entries plus the users/groups allowed to
 * use them. The API never returns the api keys: entries expose has_api_key and
 * a masked form ("****"+last4) so the key stays out of the renderer.
 *
 * @generated from message laelia.v1.ApiProvider
 */
export declare type ApiProvider = Message<"laelia.v1.ApiProvider"> & {
  /**
   * The resource name of the provider, in the form `apiProviders/{id}`.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The LLM API provider type, e.g. "deepseek" or "openrouter" (the phase-1 pi
   * runtime support set).
   *
   * @generated from field: string provider_type = 2;
   */
  providerType: string;

  /**
   * Human-readable title.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * API base URL. Empty means the provider type's default.
   *
   * @generated from field: string base_url = 4;
   */
  baseUrl: string;

  /**
   * Longer description of the provider.
   *
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * The (api_key, model) entries of this provider.
   *
   * @generated from field: repeated laelia.v1.ApiProviderEntry entries = 6;
   */
  entries: ApiProviderEntry[];

  /**
   * Users or groups allowed to use this provider, in IAM member format:
   * `users/{uid}`, `groups/{email}`, `groups/{id}`, or `allUsers`. Access is
   * checked when an agent references the provider (write-time snapshot).
   *
   * @generated from field: repeated string members = 7;
   */
  members: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp | undefined;

  /**
   * Creator's user resource name (users/{id}). Display-only.
   *
   * @generated from field: string created_by = 10;
   */
  createdBy: string;
};

/**
 * Describes the message laelia.v1.ApiProvider.
 * Use `create(ApiProviderSchema)` to create a new message.
 */
export declare const ApiProviderSchema: GenMessage<ApiProvider>;

/**
 * ApiProviderEntry is one (api_key, model) entry of an ApiProvider. The api key
 * is stored server-side and never returned; has_api_key/masked_api_key are the
 * only read surface.
 *
 * @generated from message laelia.v1.ApiProviderEntry
 */
export declare type ApiProviderEntry = Message<"laelia.v1.ApiProviderEntry"> & {
  /**
   * The entry's resource name, in the form
   * `apiProviders/{provider}/entries/{entry}`.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Optional display label to distinguish entries sharing a model.
   *
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * The model name this entry exposes (passed to the pi runtime as --model).
   *
   * @generated from field: string model = 3;
   */
  model: string;

  /**
   * Whether an api key is stored. Output only.
   *
   * @generated from field: bool has_api_key = 4;
   */
  hasApiKey: boolean;

  /**
   * Masked form of the stored key ("****"+last4), for display only. Output only.
   *
   * @generated from field: string masked_api_key = 5;
   */
  maskedApiKey: string;

  /**
   * Input only. On write: empty or a "****"-prefixed value means "keep the
   * existing key"; any other value replaces it. Never echoed on read.
   *
   * @generated from field: string api_key = 6;
   */
  apiKey: string;
};

/**
 * Describes the message laelia.v1.ApiProviderEntry.
 * Use `create(ApiProviderEntrySchema)` to create a new message.
 */
export declare const ApiProviderEntrySchema: GenMessage<ApiProviderEntry>;

/**
 * @generated from message laelia.v1.GetApiProviderRequest
 */
export declare type GetApiProviderRequest = Message<"laelia.v1.GetApiProviderRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.GetApiProviderRequest.
 * Use `create(GetApiProviderRequestSchema)` to create a new message.
 */
export declare const GetApiProviderRequestSchema: GenMessage<GetApiProviderRequest>;

/**
 * @generated from message laelia.v1.ListApiProvidersRequest
 */
export declare type ListApiProvidersRequest = Message<"laelia.v1.ListApiProvidersRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message laelia.v1.ListApiProvidersRequest.
 * Use `create(ListApiProvidersRequestSchema)` to create a new message.
 */
export declare const ListApiProvidersRequestSchema: GenMessage<ListApiProvidersRequest>;

/**
 * @generated from message laelia.v1.ListApiProvidersResponse
 */
export declare type ListApiProvidersResponse = Message<"laelia.v1.ListApiProvidersResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.ApiProvider api_providers = 1;
   */
  apiProviders: ApiProvider[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message laelia.v1.ListApiProvidersResponse.
 * Use `create(ListApiProvidersResponseSchema)` to create a new message.
 */
export declare const ListApiProvidersResponseSchema: GenMessage<ListApiProvidersResponse>;

/**
 * @generated from message laelia.v1.CreateApiProviderRequest
 */
export declare type CreateApiProviderRequest = Message<"laelia.v1.CreateApiProviderRequest"> & {
  /**
   * @generated from field: laelia.v1.ApiProvider api_provider = 1;
   */
  apiProvider?: ApiProvider | undefined;
};

/**
 * Describes the message laelia.v1.CreateApiProviderRequest.
 * Use `create(CreateApiProviderRequestSchema)` to create a new message.
 */
export declare const CreateApiProviderRequestSchema: GenMessage<CreateApiProviderRequest>;

/**
 * @generated from message laelia.v1.UpdateApiProviderRequest
 */
export declare type UpdateApiProviderRequest = Message<"laelia.v1.UpdateApiProviderRequest"> & {
  /**
   * @generated from field: laelia.v1.ApiProvider api_provider = 1;
   */
  apiProvider?: ApiProvider | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message laelia.v1.UpdateApiProviderRequest.
 * Use `create(UpdateApiProviderRequestSchema)` to create a new message.
 */
export declare const UpdateApiProviderRequestSchema: GenMessage<UpdateApiProviderRequest>;

/**
 * @generated from message laelia.v1.DeleteApiProviderRequest
 */
export declare type DeleteApiProviderRequest = Message<"laelia.v1.DeleteApiProviderRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.DeleteApiProviderRequest.
 * Use `create(DeleteApiProviderRequestSchema)` to create a new message.
 */
export declare const DeleteApiProviderRequestSchema: GenMessage<DeleteApiProviderRequest>;

/**
 * ListApiProviderModelsRequest fetches the model list a provider type exposes.
 * The api_key is a bearer credential: it is never logged and never echoed in
 * errors.
 *
 * @generated from message laelia.v1.ListApiProviderModelsRequest
 */
export declare type ListApiProviderModelsRequest = Message<"laelia.v1.ListApiProviderModelsRequest"> & {
  /**
   * @generated from field: string provider_type = 1;
   */
  providerType: string;

  /**
   * @generated from field: string api_key = 2;
   */
  apiKey: string;

  /**
   * Optional base URL override; when empty the provider type's default is used.
   *
   * @generated from field: string base_url = 3;
   */
  baseUrl: string;
};

/**
 * Describes the message laelia.v1.ListApiProviderModelsRequest.
 * Use `create(ListApiProviderModelsRequestSchema)` to create a new message.
 */
export declare const ListApiProviderModelsRequestSchema: GenMessage<ListApiProviderModelsRequest>;

/**
 * @generated from message laelia.v1.ListApiProviderModelsResponse
 */
export declare type ListApiProviderModelsResponse = Message<"laelia.v1.ListApiProviderModelsResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.PiModel models = 1;
   */
  models: PiModel[];
};

/**
 * Describes the message laelia.v1.ListApiProviderModelsResponse.
 * Use `create(ListApiProviderModelsResponseSchema)` to create a new message.
 */
export declare const ListApiProviderModelsResponseSchema: GenMessage<ListApiProviderModelsResponse>;

/**
 * ApiProviderChange is the audit payload recorded for a successful
 * CreateApiProvider/UpdateApiProvider. It carries only the provider resource
 * name and the entry names added/removed — never the api keys.
 *
 * @generated from message laelia.v1.ApiProviderChange
 */
export declare type ApiProviderChange = Message<"laelia.v1.ApiProviderChange"> & {
  /**
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * @generated from field: repeated string entries_added = 2;
   */
  entriesAdded: string[];

  /**
   * @generated from field: repeated string entries_removed = 3;
   */
  entriesRemoved: string[];
};

/**
 * Describes the message laelia.v1.ApiProviderChange.
 * Use `create(ApiProviderChangeSchema)` to create a new message.
 */
export declare const ApiProviderChangeSchema: GenMessage<ApiProviderChange>;

/**
 * ApiProviderService manages global LLM API providers. Management RPCs
 * (create/update/delete) are gated by the IAM interceptor with the
 * laelia.apiProviders.* permissions (held by workspaceAdmin or an authorized
 * custom role). ListApiProviders is handler-gated instead: it returns only the
 * providers the caller may use, so the agent create/edit form can list them
 * without a management permission.
 *
 * @generated from service laelia.v1.ApiProviderService
 */
export declare const ApiProviderService: GenService<{
  /**
   * @generated from rpc laelia.v1.ApiProviderService.GetAPIProvider
   */
  getAPIProvider: {
    methodKind: "unary";
    input: typeof GetApiProviderRequestSchema;
    output: typeof ApiProviderSchema;
  },
  /**
   * @generated from rpc laelia.v1.ApiProviderService.ListAPIProviders
   */
  listAPIProviders: {
    methodKind: "unary";
    input: typeof ListApiProvidersRequestSchema;
    output: typeof ListApiProvidersResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.ApiProviderService.CreateAPIProvider
   */
  createAPIProvider: {
    methodKind: "unary";
    input: typeof CreateApiProviderRequestSchema;
    output: typeof ApiProviderSchema;
  },
  /**
   * @generated from rpc laelia.v1.ApiProviderService.UpdateAPIProvider
   */
  updateAPIProvider: {
    methodKind: "unary";
    input: typeof UpdateApiProviderRequestSchema;
    output: typeof ApiProviderSchema;
  },
  /**
   * @generated from rpc laelia.v1.ApiProviderService.DeleteAPIProvider
   */
  deleteAPIProvider: {
    methodKind: "unary";
    input: typeof DeleteApiProviderRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * List the models a provider type exposes. The manager proxies the provider's
   * model-listing HTTP API (DeepSeek GET /models with the caller's api_key;
   * OpenRouter GET /models, public). Admin (laelia.apiProviders.update) only.
   *
   * @generated from rpc laelia.v1.ApiProviderService.ListAPIProviderModels
   */
  listAPIProviderModels: {
    methodKind: "unary";
    input: typeof ListApiProviderModelsRequestSchema;
    output: typeof ListApiProviderModelsResponseSchema;
  },
}>;

