// @generated by protoc-gen-es v2.12.0
// @generated from file v1/common.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/common.proto.
 */
export declare const file_v1_common: GenFile;

/**
 * Position in a text expressed as zero-based line and zero-based column byte
 * offset.
 *
 * @generated from message laelia.v1.Position
 */
export declare type Position = Message<"laelia.v1.Position"> & {
  /**
   * Line position in a text (zero-based).
   *
   * @generated from field: int32 line = 1;
   */
  line: number;

  /**
   * Column position in a text (zero-based), equivalent to byte offset.
   *
   * @generated from field: int32 column = 2;
   */
  column: number;
};

/**
 * Describes the message laelia.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export declare const PositionSchema: GenMessage<Position>;

/**
 * @generated from message laelia.v1.Range
 */
export declare type Range = Message<"laelia.v1.Range"> & {
  /**
   * @generated from field: int32 start = 1;
   */
  start: number;

  /**
   * @generated from field: int32 end = 2;
   */
  end: number;
};

/**
 * Describes the message laelia.v1.Range.
 * Use `create(RangeSchema)` to create a new message.
 */
export declare const RangeSchema: GenMessage<Range>;

/**
 * @generated from enum laelia.v1.State
 */
export enum State {
  /**
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: DELETED = 2;
   */
  DELETED = 2,
}

/**
 * Describes the enum laelia.v1.State.
 */
export declare const StateSchema: GenEnum<State>;

/**
 * RiskLevel is the risk level.
 *
 * @generated from enum laelia.v1.RiskLevel
 */
export enum RiskLevel {
  /**
   * @generated from enum value: RISK_LEVEL_UNSPECIFIED = 0;
   */
  RISK_LEVEL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOW = 1;
   */
  LOW = 1,

  /**
   * @generated from enum value: MODERATE = 2;
   */
  MODERATE = 2,

  /**
   * @generated from enum value: HIGH = 3;
   */
  HIGH = 3,
}

/**
 * Describes the enum laelia.v1.RiskLevel.
 */
export declare const RiskLevelSchema: GenEnum<RiskLevel>;

