// @generated by protoc-gen-es v2.12.0
// @generated from file v1/iam_service.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../google/api/annotations_pb";
import { file_google_api_field_behavior } from "../google/api/field_behavior_pb";
import { file_google_api_resource } from "../google/api/resource_pb";
import { file_store_policy } from "../store/policy_pb";
import { file_v1_annotation } from "./annotation_pb";

/**
 * Describes the file v1/iam_service.proto.
 */
export const file_v1_iam_service = /*@__PURE__*/
  fileDesc("ChR2MS9pYW1fc2VydmljZS5wcm90bxIJbGFlbGlhLnYxIkYKDUlhbVBvbGljeVZpZXcSJwoGcG9saWN5GAEgASgLMhcubGFlbGlhLnN0b3JlLklhbVBvbGljeRIMCgRldGFnGAIgASgJIh4KHEdldFdvcmtzcGFjZUlhbVBvbGljeVJlcXVlc3QiWgocU2V0V29ya3NwYWNlSWFtUG9saWN5UmVxdWVzdBIsCgZwb2xpY3kYASABKAsyFy5sYWVsaWEuc3RvcmUuSWFtUG9saWN5QgPgQQISDAoEZXRhZxgCIAEoCSI+ChhHZXRBZ2VudElhbVBvbGljeVJlcXVlc3QSIgoEbmFtZRgBIAEoCUIU4EEC+kEOCgxsYWVsaWEvQWdlbnQiegoYU2V0QWdlbnRJYW1Qb2xpY3lSZXF1ZXN0EiIKBG5hbWUYASABKAlCFOBBAvpBDgoMbGFlbGlhL0FnZW50EiwKBnBvbGljeRgCIAEoCzIXLmxhZWxpYS5zdG9yZS5JYW1Qb2xpY3lCA+BBAhIMCgRldGFnGAMgASgJMv4ECgpJYW1TZXJ2aWNlEpcBChVHZXRXb3Jrc3BhY2VJYW1Qb2xpY3kSJy5sYWVsaWEudjEuR2V0V29ya3NwYWNlSWFtUG9saWN5UmVxdWVzdBoYLmxhZWxpYS52MS5JYW1Qb2xpY3lWaWV3IjuK6jAUbGFlbGlhLmlhbS5nZXRQb2xpY3mQ6jABgtPkkwIZEhcvdjEvd29ya3NwYWNlOmlhbVBvbGljeRKeAQoVU2V0V29ya3NwYWNlSWFtUG9saWN5EicubGFlbGlhLnYxLlNldFdvcmtzcGFjZUlhbVBvbGljeVJlcXVlc3QaGC5sYWVsaWEudjEuSWFtUG9saWN5VmlldyJCiuowFGxhZWxpYS5pYW0uc2V0UG9saWN5kOowAZjqMAGC0+STAhw6ASoiFy92MS93b3Jrc3BhY2U6aWFtUG9saWN5EpUBChFHZXRBZ2VudElhbVBvbGljeRIjLmxhZWxpYS52MS5HZXRBZ2VudElhbVBvbGljeVJlcXVlc3QaGC5sYWVsaWEudjEuSWFtUG9saWN5VmlldyJBiuowFGxhZWxpYS5pYW0uZ2V0UG9saWN5kOowAYLT5JMCHxIdL3YxL3tuYW1lPWFnZW50cy8qfTppYW1Qb2xpY3kSnAEKEVNldEFnZW50SWFtUG9saWN5EiMubGFlbGlhLnYxLlNldEFnZW50SWFtUG9saWN5UmVxdWVzdBoYLmxhZWxpYS52MS5JYW1Qb2xpY3lWaWV3IkiK6jAUbGFlbGlhLmlhbS5zZXRQb2xpY3mQ6jABmOowAYLT5JMCIjoBKiIdL3YxL3tuYW1lPWFnZW50cy8qfTppYW1Qb2xpY3lCMVovZ2l0aHViLmNvbS9SYW54eS9sYWVsaWEvYmFja2VuZC9nZW5lcmF0ZWQtZ28vdjFiBnByb3RvMw", [file_google_api_annotations, file_google_api_field_behavior, file_google_api_resource, file_store_policy, file_v1_annotation]);

/**
 * Describes the message laelia.v1.IamPolicyView.
 * Use `create(IamPolicyViewSchema)` to create a new message.
 */
export const IamPolicyViewSchema = /*@__PURE__*/
  messageDesc(file_v1_iam_service, 0);

/**
 * Describes the message laelia.v1.GetWorkspaceIamPolicyRequest.
 * Use `create(GetWorkspaceIamPolicyRequestSchema)` to create a new message.
 */
export const GetWorkspaceIamPolicyRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_iam_service, 1);

/**
 * Describes the message laelia.v1.SetWorkspaceIamPolicyRequest.
 * Use `create(SetWorkspaceIamPolicyRequestSchema)` to create a new message.
 */
export const SetWorkspaceIamPolicyRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_iam_service, 2);

/**
 * Describes the message laelia.v1.GetAgentIamPolicyRequest.
 * Use `create(GetAgentIamPolicyRequestSchema)` to create a new message.
 */
export const GetAgentIamPolicyRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_iam_service, 3);

/**
 * Describes the message laelia.v1.SetAgentIamPolicyRequest.
 * Use `create(SetAgentIamPolicyRequestSchema)` to create a new message.
 */
export const SetAgentIamPolicyRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_iam_service, 4);

/**
 * IamService exposes the workspace and per-agent IAM policies for management.
 * Get reads the full policy; Set replaces it whole, guarded by an etag. Each
 * RPC is gated by the IAM interceptor with laelia.iam.getPolicy / setPolicy.
 *
 * @generated from service laelia.v1.IamService
 */
export const IamService = /*@__PURE__*/
  serviceDesc(file_v1_iam_service, 0);

