// @generated by protoc-gen-es v2.12.0
// @generated from file v1/mcp.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { EmptySchema, FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file v1/mcp.proto.
 */
export declare const file_v1_mcp: GenFile;

/**
 * McpServer is a workspace-global, admin-managed MCP service. The manager holds
 * the full transport configuration (URL and header values) and only exposes a
 * per-agent tool catalog to machines; header values are masked on read.
 *
 * @generated from message laelia.v1.McpServer
 */
export declare type McpServer = Message<"laelia.v1.McpServer"> & {
  /**
   * The resource name of the MCP server, in the form `mcpServers/{id}`.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Human-readable title.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Longer description of the MCP server.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Transport configuration. Exactly one of http/sse must be set.
   *
   * @generated from oneof laelia.v1.McpServer.transport
   */
  transport: {
    /**
     * Streamable HTTP transport.
     *
     * @generated from field: laelia.v1.McpHttpTransport http = 4;
     */
    value: McpHttpTransport;
    case: "http";
  } | {
    /**
     * SSE transport.
     *
     * @generated from field: laelia.v1.McpSseTransport sse = 5;
     */
    value: McpSseTransport;
    case: "sse";
  } | { case: undefined; value?: undefined };

  /**
   * Users or groups allowed to use this MCP server, in IAM member format:
   * `users/{uid}`, `groups/{email}`, `groups/{id}`, or `allUsers`. Access is
   * checked when an agent references the server (and again at call time).
   *
   * @generated from field: repeated string members = 6;
   */
  members: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp | undefined;

  /**
   * Creator's user resource name (users/{id}). Display-only.
   *
   * @generated from field: string created_by = 9;
   */
  createdBy: string;

  /**
   * config_version increments on every update. The agent gateway returns it in
   * the tool catalog and re-checks it at call time so stale catalogs fail
   * closed instead of silently running against changed server configuration.
   *
   * @generated from field: int64 config_version = 10;
   */
  configVersion: bigint;
};

/**
 * Describes the message laelia.v1.McpServer.
 * Use `create(McpServerSchema)` to create a new message.
 */
export declare const McpServerSchema: GenMessage<McpServer>;

/**
 * McpHttpTransport is a streamable-HTTP MCP transport.
 *
 * @generated from message laelia.v1.McpHttpTransport
 */
export declare type McpHttpTransport = Message<"laelia.v1.McpHttpTransport"> & {
  /**
   * The MCP streamable HTTP endpoint URL, e.g. "https://mcp.example.com/mcp".
   *
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * Headers sent with every request to the MCP server (typically
   * Authorization). Values are stored server-side and masked on read.
   *
   * @generated from field: repeated laelia.v1.McpHeader headers = 2;
   */
  headers: McpHeader[];
};

/**
 * Describes the message laelia.v1.McpHttpTransport.
 * Use `create(McpHttpTransportSchema)` to create a new message.
 */
export declare const McpHttpTransportSchema: GenMessage<McpHttpTransport>;

/**
 * McpSseTransport is an SSE MCP transport. The messages endpoint is derived
 * from the standard MCP SSE layout (`GET url` for the event stream and
 * `POST /messages?session_id=...` on the same origin).
 *
 * @generated from message laelia.v1.McpSseTransport
 */
export declare type McpSseTransport = Message<"laelia.v1.McpSseTransport"> & {
  /**
   * The MCP SSE endpoint URL, e.g. "https://mcp.example.com/sse".
   *
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * Headers sent with requests to the MCP server. Values are stored
   * server-side and masked on read.
   *
   * @generated from field: repeated laelia.v1.McpHeader headers = 2;
   */
  headers: McpHeader[];
};

/**
 * Describes the message laelia.v1.McpSseTransport.
 * Use `create(McpSseTransportSchema)` to create a new message.
 */
export declare const McpSseTransportSchema: GenMessage<McpSseTransport>;

/**
 * McpHeader is one HTTP header attached to MCP transport requests. On write a
 * masked ("****"-prefixed) or empty value means "keep the stored value".
 *
 * @generated from message laelia.v1.McpHeader
 */
export declare type McpHeader = Message<"laelia.v1.McpHeader"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;

  /**
   * @generated from field: string masked_value = 3;
   */
  maskedValue: string;
};

/**
 * Describes the message laelia.v1.McpHeader.
 * Use `create(McpHeaderSchema)` to create a new message.
 */
export declare const McpHeaderSchema: GenMessage<McpHeader>;

/**
 * @generated from message laelia.v1.GetMcpServerRequest
 */
export declare type GetMcpServerRequest = Message<"laelia.v1.GetMcpServerRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.GetMcpServerRequest.
 * Use `create(GetMcpServerRequestSchema)` to create a new message.
 */
export declare const GetMcpServerRequestSchema: GenMessage<GetMcpServerRequest>;

/**
 * @generated from message laelia.v1.ListMcpServersRequest
 */
export declare type ListMcpServersRequest = Message<"laelia.v1.ListMcpServersRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message laelia.v1.ListMcpServersRequest.
 * Use `create(ListMcpServersRequestSchema)` to create a new message.
 */
export declare const ListMcpServersRequestSchema: GenMessage<ListMcpServersRequest>;

/**
 * @generated from message laelia.v1.ListMcpServersResponse
 */
export declare type ListMcpServersResponse = Message<"laelia.v1.ListMcpServersResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.McpServer mcp_servers = 1;
   */
  mcpServers: McpServer[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message laelia.v1.ListMcpServersResponse.
 * Use `create(ListMcpServersResponseSchema)` to create a new message.
 */
export declare const ListMcpServersResponseSchema: GenMessage<ListMcpServersResponse>;

/**
 * @generated from message laelia.v1.CreateMcpServerRequest
 */
export declare type CreateMcpServerRequest = Message<"laelia.v1.CreateMcpServerRequest"> & {
  /**
   * @generated from field: laelia.v1.McpServer mcp_server = 1;
   */
  mcpServer?: McpServer | undefined;
};

/**
 * Describes the message laelia.v1.CreateMcpServerRequest.
 * Use `create(CreateMcpServerRequestSchema)` to create a new message.
 */
export declare const CreateMcpServerRequestSchema: GenMessage<CreateMcpServerRequest>;

/**
 * @generated from message laelia.v1.UpdateMcpServerRequest
 */
export declare type UpdateMcpServerRequest = Message<"laelia.v1.UpdateMcpServerRequest"> & {
  /**
   * @generated from field: laelia.v1.McpServer mcp_server = 1;
   */
  mcpServer?: McpServer | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message laelia.v1.UpdateMcpServerRequest.
 * Use `create(UpdateMcpServerRequestSchema)` to create a new message.
 */
export declare const UpdateMcpServerRequestSchema: GenMessage<UpdateMcpServerRequest>;

/**
 * @generated from message laelia.v1.DeleteMcpServerRequest
 */
export declare type DeleteMcpServerRequest = Message<"laelia.v1.DeleteMcpServerRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.DeleteMcpServerRequest.
 * Use `create(DeleteMcpServerRequestSchema)` to create a new message.
 */
export declare const DeleteMcpServerRequestSchema: GenMessage<DeleteMcpServerRequest>;

/**
 * McpServerChange is the audit payload recorded for a successful
 * CreateMcpServer/UpdateMcpServer. It carries only the server resource name —
 * never header values.
 *
 * @generated from message laelia.v1.McpServerChange
 */
export declare type McpServerChange = Message<"laelia.v1.McpServerChange"> & {
  /**
   * @generated from field: string server = 1;
   */
  server: string;
};

/**
 * Describes the message laelia.v1.McpServerChange.
 * Use `create(McpServerChangeSchema)` to create a new message.
 */
export declare const McpServerChangeSchema: GenMessage<McpServerChange>;

/**
 * McpTool is one tool in a per-agent MCP tool catalog. The catalog is computed
 * by the manager from the agent's enabled MCP servers and the servers' current
 * tool lists; machines never see the transport configuration.
 *
 * @generated from message laelia.v1.McpTool
 */
export declare type McpTool = Message<"laelia.v1.McpTool"> & {
  /**
   * mcp_servers/{id} the tool belongs to.
   *
   * @generated from field: string mcp_server_id = 1;
   */
  mcpServerId: string;

  /**
   * Display name of the MCP server.
   *
   * @generated from field: string server_name = 2;
   */
  serverName: string;

  /**
   * The real MCP tool name on the server.
   *
   * @generated from field: string tool_name = 3;
   */
  toolName: string;

  /**
   * The name exposed to the runtime; collision-scoped per server.
   *
   * @generated from field: string runtime_name = 4;
   */
  runtimeName: string;

  /**
   * @generated from field: string title = 5;
   */
  title: string;

  /**
   * @generated from field: string description = 6;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Struct input_schema = 7;
   */
  inputSchema?: JsonObject | undefined;

  /**
   * @generated from field: int64 config_version = 8;
   */
  configVersion: bigint;

  /**
   * @generated from field: int64 assignment_version = 9;
   */
  assignmentVersion: bigint;
};

/**
 * Describes the message laelia.v1.McpTool.
 * Use `create(McpToolSchema)` to create a new message.
 */
export declare const McpToolSchema: GenMessage<McpTool>;

/**
 * @generated from message laelia.v1.GetMcpCatalogRequest
 */
export declare type GetMcpCatalogRequest = Message<"laelia.v1.GetMcpCatalogRequest"> & {
};

/**
 * Describes the message laelia.v1.GetMcpCatalogRequest.
 * Use `create(GetMcpCatalogRequestSchema)` to create a new message.
 */
export declare const GetMcpCatalogRequestSchema: GenMessage<GetMcpCatalogRequest>;

/**
 * @generated from message laelia.v1.GetMcpCatalogResponse
 */
export declare type GetMcpCatalogResponse = Message<"laelia.v1.GetMcpCatalogResponse"> & {
  /**
   * catalog_version is the catalog contract version. Currently always 1.
   *
   * @generated from field: int32 catalog_version = 1;
   */
  catalogVersion: number;

  /**
   * @generated from field: repeated laelia.v1.McpTool tools = 2;
   */
  tools: McpTool[];
};

/**
 * Describes the message laelia.v1.GetMcpCatalogResponse.
 * Use `create(GetMcpCatalogResponseSchema)` to create a new message.
 */
export declare const GetMcpCatalogResponseSchema: GenMessage<GetMcpCatalogResponse>;

/**
 * @generated from message laelia.v1.CallMcpToolRequest
 */
export declare type CallMcpToolRequest = Message<"laelia.v1.CallMcpToolRequest"> & {
  /**
   * @generated from field: string mcp_server_id = 1;
   */
  mcpServerId: string;

  /**
   * @generated from field: string tool_name = 2;
   */
  toolName: string;

  /**
   * @generated from field: google.protobuf.Struct arguments = 3;
   */
  arguments?: JsonObject | undefined;

  /**
   * @generated from field: int64 expected_config_version = 4;
   */
  expectedConfigVersion: bigint;

  /**
   * @generated from field: int64 expected_assignment_version = 5;
   */
  expectedAssignmentVersion: bigint;
};

/**
 * Describes the message laelia.v1.CallMcpToolRequest.
 * Use `create(CallMcpToolRequestSchema)` to create a new message.
 */
export declare const CallMcpToolRequestSchema: GenMessage<CallMcpToolRequest>;

/**
 * @generated from message laelia.v1.CallMcpToolResponse
 */
export declare type CallMcpToolResponse = Message<"laelia.v1.CallMcpToolResponse"> & {
  /**
   * Content blocks of the MCP tool result (text/image).
   *
   * @generated from field: repeated laelia.v1.McpContentBlock content = 1;
   */
  content: McpContentBlock[];

  /**
   * @generated from field: bool is_error = 2;
   */
  isError: boolean;

  /**
   * @generated from field: google.protobuf.Struct structured_content = 3;
   */
  structuredContent?: JsonObject | undefined;
};

/**
 * Describes the message laelia.v1.CallMcpToolResponse.
 * Use `create(CallMcpToolResponseSchema)` to create a new message.
 */
export declare const CallMcpToolResponseSchema: GenMessage<CallMcpToolResponse>;

/**
 * @generated from message laelia.v1.McpContentBlock
 */
export declare type McpContentBlock = Message<"laelia.v1.McpContentBlock"> & {
  /**
   * @generated from oneof laelia.v1.McpContentBlock.kind
   */
  kind: {
    /**
     * @generated from field: laelia.v1.McpTextContent text = 1;
     */
    value: McpTextContent;
    case: "text";
  } | {
    /**
     * @generated from field: laelia.v1.McpImageContent image = 2;
     */
    value: McpImageContent;
    case: "image";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message laelia.v1.McpContentBlock.
 * Use `create(McpContentBlockSchema)` to create a new message.
 */
export declare const McpContentBlockSchema: GenMessage<McpContentBlock>;

/**
 * @generated from message laelia.v1.McpTextContent
 */
export declare type McpTextContent = Message<"laelia.v1.McpTextContent"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message laelia.v1.McpTextContent.
 * Use `create(McpTextContentSchema)` to create a new message.
 */
export declare const McpTextContentSchema: GenMessage<McpTextContent>;

/**
 * @generated from message laelia.v1.McpImageContent
 */
export declare type McpImageContent = Message<"laelia.v1.McpImageContent"> & {
  /**
   * base64-encoded image data
   *
   * @generated from field: string data = 1;
   */
  data: string;

  /**
   * @generated from field: string mime_type = 2;
   */
  mimeType: string;
};

/**
 * Describes the message laelia.v1.McpImageContent.
 * Use `create(McpImageContentSchema)` to create a new message.
 */
export declare const McpImageContentSchema: GenMessage<McpImageContent>;

/**
 * McpServerService manages the workspace MCP server registry. Management RPCs
 * are gated by the IAM interceptor with the laelia.mcpServers.* permissions
 * (held by workspaceAdmin or an authorized custom role). ListMcpServers is
 * handler-gated instead: it returns only the servers the caller may use, so
 * the agent config form can list them without a management permission.
 *
 * @generated from service laelia.v1.McpServerService
 */
export declare const McpServerService: GenService<{
  /**
   * @generated from rpc laelia.v1.McpServerService.GetMcpServer
   */
  getMcpServer: {
    methodKind: "unary";
    input: typeof GetMcpServerRequestSchema;
    output: typeof McpServerSchema;
  },
  /**
   * @generated from rpc laelia.v1.McpServerService.ListMcpServers
   */
  listMcpServers: {
    methodKind: "unary";
    input: typeof ListMcpServersRequestSchema;
    output: typeof ListMcpServersResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.McpServerService.CreateMcpServer
   */
  createMcpServer: {
    methodKind: "unary";
    input: typeof CreateMcpServerRequestSchema;
    output: typeof McpServerSchema;
  },
  /**
   * @generated from rpc laelia.v1.McpServerService.UpdateMcpServer
   */
  updateMcpServer: {
    methodKind: "unary";
    input: typeof UpdateMcpServerRequestSchema;
    output: typeof McpServerSchema;
  },
  /**
   * @generated from rpc laelia.v1.McpServerService.DeleteMcpServer
   */
  deleteMcpServer: {
    methodKind: "unary";
    input: typeof DeleteMcpServerRequestSchema;
    output: typeof EmptySchema;
  },
}>;

/**
 * McpGatewayService is the agent-facing gateway: machines call it to fetch the
 * current authorized MCP tool catalog for an agent and to invoke allowlisted
 * tools. Callers are authenticated as an agent (machine token + X-Laelia-Agent
 * header); every call re-checks the caller's current authorization.
 *
 * @generated from service laelia.v1.McpGatewayService
 */
export declare const McpGatewayService: GenService<{
  /**
   * @generated from rpc laelia.v1.McpGatewayService.GetMcpCatalog
   */
  getMcpCatalog: {
    methodKind: "unary";
    input: typeof GetMcpCatalogRequestSchema;
    output: typeof GetMcpCatalogResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.McpGatewayService.CallMcpTool
   */
  callMcpTool: {
    methodKind: "unary";
    input: typeof CallMcpToolRequestSchema;
    output: typeof CallMcpToolResponseSchema;
  },
}>;

