// @generated by protoc-gen-es v2.12.0
// @generated from file v1/provisioner.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import type { Ping, Pong } from "./command_pb";
import type { MachineSchema, ProvisioningPhase } from "./machine_pb";

/**
 * Describes the file v1/provisioner.proto.
 */
export declare const file_v1_provisioner: GenFile;

/**
 * @generated from message laelia.v1.CreateProvisionerRequest
 */
export declare type CreateProvisionerRequest = Message<"laelia.v1.CreateProvisionerRequest"> & {
  /**
   * The provisioner to create: title, backend, and optional description.
   *
   * @generated from field: laelia.v1.Provisioner provisioner = 1;
   */
  provisioner?: Provisioner | undefined;
};

/**
 * Describes the message laelia.v1.CreateProvisionerRequest.
 * Use `create(CreateProvisionerRequestSchema)` to create a new message.
 */
export declare const CreateProvisionerRequestSchema: GenMessage<CreateProvisionerRequest>;

/**
 * @generated from message laelia.v1.CreateProvisionerResponse
 */
export declare type CreateProvisionerResponse = Message<"laelia.v1.CreateProvisionerResponse"> & {
  /**
   * @generated from field: laelia.v1.Provisioner provisioner = 1;
   */
  provisioner?: Provisioner | undefined;

  /**
   * The one-time provisioner token; never stored server-side in plaintext and
   * never returned again. Shown in a copy-once dialog.
   *
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message laelia.v1.CreateProvisionerResponse.
 * Use `create(CreateProvisionerResponseSchema)` to create a new message.
 */
export declare const CreateProvisionerResponseSchema: GenMessage<CreateProvisionerResponse>;

/**
 * @generated from message laelia.v1.ListProvisionersRequest
 */
export declare type ListProvisionersRequest = Message<"laelia.v1.ListProvisionersRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: bool show_deleted = 3;
   */
  showDeleted: boolean;
};

/**
 * Describes the message laelia.v1.ListProvisionersRequest.
 * Use `create(ListProvisionersRequestSchema)` to create a new message.
 */
export declare const ListProvisionersRequestSchema: GenMessage<ListProvisionersRequest>;

/**
 * @generated from message laelia.v1.ListProvisionersResponse
 */
export declare type ListProvisionersResponse = Message<"laelia.v1.ListProvisionersResponse"> & {
  /**
   * @generated from field: repeated laelia.v1.Provisioner provisioners = 1;
   */
  provisioners: Provisioner[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message laelia.v1.ListProvisionersResponse.
 * Use `create(ListProvisionersResponseSchema)` to create a new message.
 */
export declare const ListProvisionersResponseSchema: GenMessage<ListProvisionersResponse>;

/**
 * @generated from message laelia.v1.GetProvisionerRequest
 */
export declare type GetProvisionerRequest = Message<"laelia.v1.GetProvisionerRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.GetProvisionerRequest.
 * Use `create(GetProvisionerRequestSchema)` to create a new message.
 */
export declare const GetProvisionerRequestSchema: GenMessage<GetProvisionerRequest>;

/**
 * @generated from message laelia.v1.RotateProvisionerTokenRequest
 */
export declare type RotateProvisionerTokenRequest = Message<"laelia.v1.RotateProvisionerTokenRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * audit purpose
   *
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message laelia.v1.RotateProvisionerTokenRequest.
 * Use `create(RotateProvisionerTokenRequestSchema)` to create a new message.
 */
export declare const RotateProvisionerTokenRequestSchema: GenMessage<RotateProvisionerTokenRequest>;

/**
 * @generated from message laelia.v1.RotateProvisionerTokenResponse
 */
export declare type RotateProvisionerTokenResponse = Message<"laelia.v1.RotateProvisionerTokenResponse"> & {
  /**
   * @generated from field: laelia.v1.Provisioner provisioner = 1;
   */
  provisioner?: Provisioner | undefined;

  /**
   * The new one-time token; see CreateProvisionerResponse.token.
   *
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message laelia.v1.RotateProvisionerTokenResponse.
 * Use `create(RotateProvisionerTokenResponseSchema)` to create a new message.
 */
export declare const RotateProvisionerTokenResponseSchema: GenMessage<RotateProvisionerTokenResponse>;

/**
 * @generated from message laelia.v1.DeleteProvisionerRequest
 */
export declare type DeleteProvisionerRequest = Message<"laelia.v1.DeleteProvisionerRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message laelia.v1.DeleteProvisionerRequest.
 * Use `create(DeleteProvisionerRequestSchema)` to create a new message.
 */
export declare const DeleteProvisionerRequestSchema: GenMessage<DeleteProvisionerRequest>;

/**
 * @generated from message laelia.v1.ProvisionMachineRequest
 */
export declare type ProvisionMachineRequest = Message<"laelia.v1.ProvisionMachineRequest"> & {
  /**
   * The provisioner that will create the workload, provisioners/{id}.
   *
   * @generated from field: string provisioner = 1;
   */
  provisioner: string;

  /**
   * Machine title.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Target owner, users/{id}. Empty = caller. Naming another user requires a
   * workspace admin (checked in the handler, like machine ownership transfer).
   *
   * @generated from field: string owner = 3;
   */
  owner: string;

  /**
   * Optional custom runtime image for this machine's workload, overriding the
   * workspace ProvisioningSetting.runtime_image default. Must be a valid image
   * reference and match the admin-configured custom-image allowlist (an empty
   * allowlist disables custom images). Persisted on the machine so replayed
   * provisioning jobs rebuild the same workload.
   *
   * @generated from field: string runtime_image = 4;
   */
  runtimeImage: string;

  /**
   * Per-machine parameter overrides keyed by catalog key ("cpu", "memory",
   * "disk", ...). Every key must be declared by the target provisioner's
   * schema and pass its type/bounds validation; values persist on the machine
   * so replayed provisioning jobs rebuild the same workload. Empty = the
   * provisioner's configured defaults.
   *
   * @generated from field: map<string, string> machine_params = 5;
   */
  machineParams: { [key: string]: string };
};

/**
 * Describes the message laelia.v1.ProvisionMachineRequest.
 * Use `create(ProvisionMachineRequestSchema)` to create a new message.
 */
export declare const ProvisionMachineRequestSchema: GenMessage<ProvisionMachineRequest>;

/**
 * MachineParamSpec is one provisioner-declared machine parameter: a
 * manager-catalog key plus per-instance constraints reported in
 * ProvisionerReady and persisted in the provisioner status. The UI renders
 * the create form from this list.
 *
 * @generated from message laelia.v1.MachineParamSpec
 */
export declare type MachineParamSpec = Message<"laelia.v1.MachineParamSpec"> & {
  /**
   * Catalog key, e.g. "cpu" | "memory" | "disk" | "storage_class".
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * Type resolved by the manager from the catalog.
   *
   * @generated from field: laelia.v1.MachineParamType type = 2;
   */
  type: MachineParamType;

  /**
   * @generated from field: bool required = 3;
   */
  required: boolean;

  /**
   * Default from the provisioner config; empty = the backend's built-in
   * default (shown as the form placeholder; untouched fields keep tracking
   * the admin config).
   *
   * @generated from field: string default_value = 4;
   */
  defaultValue: string;

  /**
   * Inclusive bounds for QUANTITY params; empty = unbounded on that side.
   *
   * @generated from field: string min_value = 5;
   */
  minValue: string;

  /**
   * @generated from field: string max_value = 6;
   */
  maxValue: string;

  /**
   * Allowed values for constrained params (none today); empty = free-form.
   *
   * @generated from field: repeated string options = 7;
   */
  options: string[];
};

/**
 * Describes the message laelia.v1.MachineParamSpec.
 * Use `create(MachineParamSpecSchema)` to create a new message.
 */
export declare const MachineParamSpecSchema: GenMessage<MachineParamSpec>;

/**
 * Provisioner is a registered worker that creates machine workloads in one
 * virtualization backend on the manager's behalf.
 *
 * @generated from message laelia.v1.Provisioner
 */
export declare type Provisioner = Message<"laelia.v1.Provisioner"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Backend type ("kubernetes", "docker", ...). Free-form; the UI lists known
   * backends and shows others as registered-but-unsupported.
   *
   * @generated from field: string backend = 3;
   */
  backend: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: laelia.v1.ProvisionerStatus status = 5;
   */
  status?: ProvisionerStatus | undefined;

  /**
   * Live (non-deleted) machines bound to this provisioner.
   *
   * @generated from field: int32 machine_count = 6;
   */
  machineCount: number;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;

  /**
   * Creator's user resource name (users/{id}).
   *
   * @generated from field: string created_by = 8;
   */
  createdBy: string;
};

/**
 * Describes the message laelia.v1.Provisioner.
 * Use `create(ProvisionerSchema)` to create a new message.
 */
export declare const ProvisionerSchema: GenMessage<Provisioner>;

/**
 * ProvisionerStatus is the runtime status of a provisioner, derived from its
 * ProvisionerChannel stream.
 *
 * @generated from message laelia.v1.ProvisionerStatus
 */
export declare type ProvisionerStatus = Message<"laelia.v1.ProvisionerStatus"> & {
  /**
   * @generated from field: bool connected = 1;
   */
  connected: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp last_seen = 2;
   */
  lastSeen?: Timestamp | undefined;

  /**
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * @generated from field: string backend = 4;
   */
  backend: string;

  /**
   * @generated from field: bool auto_upgrade = 5;
   */
  autoUpgrade: boolean;

  /**
   * @generated from field: string config_digest = 6;
   */
  configDigest: string;

  /**
   * RetainData echoes the provisioner's configured data retention; the
   * manager sends it as keep_data on teardown jobs (design §6.4).
   *
   * @generated from field: bool retain_data = 7;
   */
  retainData: boolean;

  /**
   * MachineParams is the parameter schema reported in the last
   * ProvisionerReady frame (manager-catalog keys only, types resolved
   * manager-side), so the create form renders even while offline.
   *
   * @generated from field: repeated laelia.v1.MachineParamSpec machine_params = 8;
   */
  machineParams: MachineParamSpec[];
};

/**
 * Describes the message laelia.v1.ProvisionerStatus.
 * Use `create(ProvisionerStatusSchema)` to create a new message.
 */
export declare const ProvisionerStatusSchema: GenMessage<ProvisionerStatus>;

/**
 * @generated from message laelia.v1.ProvisionerStreamMessage
 */
export declare type ProvisionerStreamMessage = Message<"laelia.v1.ProvisionerStreamMessage"> & {
  /**
   * @generated from oneof laelia.v1.ProvisionerStreamMessage.message
   */
  message: {
    /**
     * First frame after connect: version, backend, capabilities, config digest.
     *
     * @generated from field: laelia.v1.ProvisionerReady ready = 1;
     */
    value: ProvisionerReady;
    case: "ready";
  } | {
    /**
     * @generated from field: laelia.v1.ProvisionJobProgress job_progress = 2;
     */
    value: ProvisionJobProgress;
    case: "jobProgress";
  } | {
    /**
     * @generated from field: laelia.v1.Ping ping = 3;
     */
    value: Ping;
    case: "ping";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message laelia.v1.ProvisionerStreamMessage.
 * Use `create(ProvisionerStreamMessageSchema)` to create a new message.
 */
export declare const ProvisionerStreamMessageSchema: GenMessage<ProvisionerStreamMessage>;

/**
 * @generated from message laelia.v1.ManagerProvisionerStreamMessage
 */
export declare type ManagerProvisionerStreamMessage = Message<"laelia.v1.ManagerProvisionerStreamMessage"> & {
  /**
   * @generated from oneof laelia.v1.ManagerProvisionerStreamMessage.message
   */
  message: {
    /**
     * @generated from field: laelia.v1.ProvisionMachineJob provision_job = 1;
     */
    value: ProvisionMachineJob;
    case: "provisionJob";
  } | {
    /**
     * @generated from field: laelia.v1.DeprovisionMachineJob deprovision_job = 2;
     */
    value: DeprovisionMachineJob;
    case: "deprovisionJob";
  } | {
    /**
     * @generated from field: laelia.v1.Pong pong = 3;
     */
    value: Pong;
    case: "pong";
  } | {
    /**
     * DisconnectNotice warns the provisioner its token was rotated or the
     * provisioner deleted, so it can stop retrying with a dead credential.
     *
     * @generated from field: laelia.v1.ProvisionerDisconnectNotice disconnect_notice = 4;
     */
    value: ProvisionerDisconnectNotice;
    case: "disconnectNotice";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message laelia.v1.ManagerProvisionerStreamMessage.
 * Use `create(ManagerProvisionerStreamMessageSchema)` to create a new message.
 */
export declare const ManagerProvisionerStreamMessageSchema: GenMessage<ManagerProvisionerStreamMessage>;

/**
 * @generated from message laelia.v1.ProvisionerReady
 */
export declare type ProvisionerReady = Message<"laelia.v1.ProvisionerReady"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: string backend = 2;
   */
  backend: string;

  /**
   * @generated from field: repeated string capabilities = 3;
   */
  capabilities: string[];

  /**
   * Short hash of the provisioner's effective config, surfaced for drift
   * visibility (e.g. a manager_url_override in effect).
   *
   * @generated from field: string config_digest = 4;
   */
  configDigest: string;

  /**
   * AutoUpgrade echoes the provisioner's config flag; persisted in the
   * provisioner status and honored by the manager's auto-upgrade loop.
   *
   * @generated from field: bool auto_upgrade = 5;
   */
  autoUpgrade: boolean;

  /**
   * RetainData echoes the provisioner's config flag; persisted in the
   * provisioner status and used as keep_data on teardown jobs (design §6.4).
   *
   * @generated from field: bool retain_data = 6;
   */
  retainData: boolean;

  /**
   * MachineParams is the machine-parameter schema this provisioner instance
   * accepts: manager-catalog keys with per-instance defaults and bounds
   * sourced from its config. The manager validates and filters it (unknown
   * catalog keys are dropped) before persisting.
   *
   * @generated from field: repeated laelia.v1.MachineParamSpec machine_params = 7;
   */
  machineParams: MachineParamSpec[];
};

/**
 * Describes the message laelia.v1.ProvisionerReady.
 * Use `create(ProvisionerReadySchema)` to create a new message.
 */
export declare const ProvisionerReadySchema: GenMessage<ProvisionerReady>;

/**
 * ProvisionMachineJob carries everything the provisioner needs to create one
 * machine workload. The refresh token is the machine's durable credential:
 * the provisioner stores it in a backend secret (never in a CR) and the pod
 * picks it up at first boot.
 *
 * @generated from message laelia.v1.ProvisionMachineJob
 */
export declare type ProvisionMachineJob = Message<"laelia.v1.ProvisionMachineJob"> & {
  /**
   * machines/{uuid}
   *
   * @generated from field: string machine = 1;
   */
  machine: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Owner display handle; display only (the provisioner never needs it).
   *
   * @generated from field: string owner_handle = 3;
   */
  ownerHandle: string;

  /**
   * The machine's refresh token, minted by the manager for the machine named
   * above, bound to fingerprint.
   *
   * @generated from field: string refresh_token = 4;
   */
  refreshToken: string;

  /**
   * The connection fingerprint the machine will present (LAELIA_FINGERPRINT).
   *
   * @generated from field: string fingerprint = 5;
   */
  fingerprint: string;

  /**
   * URL pods use to download binaries from and connect to the manager.
   *
   * @generated from field: string manager_url = 6;
   */
  managerUrl: string;

  /**
   * Runtime image for the pod (no machine binary inside; downloaded at boot).
   *
   * @generated from field: string runtime_image = 7;
   */
  runtimeImage: string;

  /**
   * Machine binary target to install, e.g. "linux-x64".
   *
   * @generated from field: string binary_target = 8;
   */
  binaryTarget: string;

  /**
   * @generated from field: map<string, string> machine_labels = 9;
   */
  machineLabels: { [key: string]: string };

  /**
   * The manager-rendered bootstrap script (init container payload).
   *
   * @generated from field: string bootstrap_script = 10;
   */
  bootstrapScript: string;

  /**
   * User-provided parameter overrides (catalog-keyed), validated manager-side
   * at ProvisionMachine time. Backends merge them over their own config
   * defaults, applying only keys they know; replayed jobs carry them
   * verbatim.
   *
   * @generated from field: map<string, string> machine_params = 11;
   */
  machineParams: { [key: string]: string };
};

/**
 * Describes the message laelia.v1.ProvisionMachineJob.
 * Use `create(ProvisionMachineJobSchema)` to create a new message.
 */
export declare const ProvisionMachineJobSchema: GenMessage<ProvisionMachineJob>;

/**
 * @generated from message laelia.v1.DeprovisionMachineJob
 */
export declare type DeprovisionMachineJob = Message<"laelia.v1.DeprovisionMachineJob"> & {
  /**
   * @generated from field: string machine = 1;
   */
  machine: string;

  /**
   * keep_data preserves the machine's data volume when the backend supports
   * retention; default (false) deletes it with the workload.
   *
   * @generated from field: bool keep_data = 2;
   */
  keepData: boolean;
};

/**
 * Describes the message laelia.v1.DeprovisionMachineJob.
 * Use `create(DeprovisionMachineJobSchema)` to create a new message.
 */
export declare const DeprovisionMachineJobSchema: GenMessage<DeprovisionMachineJob>;

/**
 * ProvisionJobProgress is the provisioner's report on one provisioning job.
 * Manager-side phase transitions are driven purely by these frames; the
 * manager never guesses cluster state.
 *
 * @generated from message laelia.v1.ProvisionJobProgress
 */
export declare type ProvisionJobProgress = Message<"laelia.v1.ProvisionJobProgress"> & {
  /**
   * @generated from field: string machine = 1;
   */
  machine: string;

  /**
   * @generated from field: laelia.v1.ProvisioningPhase phase = 2;
   */
  phase: ProvisioningPhase;

  /**
   * @generated from field: string error = 3;
   */
  error: string;

  /**
   * Backend-specific locator, e.g. "laelia-machines/laelia-machine-abc123".
   *
   * @generated from field: string workload_name = 4;
   */
  workloadName: string;
};

/**
 * Describes the message laelia.v1.ProvisionJobProgress.
 * Use `create(ProvisionJobProgressSchema)` to create a new message.
 */
export declare const ProvisionJobProgressSchema: GenMessage<ProvisionJobProgress>;

/**
 * @generated from message laelia.v1.ProvisionerDisconnectNotice
 */
export declare type ProvisionerDisconnectNotice = Message<"laelia.v1.ProvisionerDisconnectNotice"> & {
  /**
   * @generated from field: string reason = 1;
   */
  reason: string;

  /**
   * deleted is true when the provisioner was permanently deleted (not just
   * rotated): the operator should tear down its own hosting (scale its
   * Deployment to 0) so it stops crash-looping with a dead credential. The
   * Deployment/CRD/RBAC/namespace remain for the user to clean up manually.
   *
   * @generated from field: bool deleted = 2;
   */
  deleted: boolean;
};

/**
 * Describes the message laelia.v1.ProvisionerDisconnectNotice.
 * Use `create(ProvisionerDisconnectNoticeSchema)` to create a new message.
 */
export declare const ProvisionerDisconnectNoticeSchema: GenMessage<ProvisionerDisconnectNotice>;

/**
 * MachineParamType is the value type of one catalog parameter, resolved by
 * the manager from its catalog (the provisioner reports keys, not types).
 *
 * @generated from enum laelia.v1.MachineParamType
 */
export enum MachineParamType {
  /**
   * @generated from enum value: MACHINE_PARAM_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * QUANTITY is a k8s-style quantity string ("500m", "2Gi").
   *
   * @generated from enum value: MACHINE_PARAM_TYPE_QUANTITY = 1;
   */
  QUANTITY = 1,

  /**
   * STRING is a DNS-1123-label-safe string (e.g. a storage class name).
   *
   * @generated from enum value: MACHINE_PARAM_TYPE_STRING = 2;
   */
  STRING = 2,
}

/**
 * Describes the enum laelia.v1.MachineParamType.
 */
export declare const MachineParamTypeSchema: GenEnum<MachineParamType>;

/**
 * ProvisionerService manages provisioners (management-plane workers that
 * create machine workloads in a customer's infrastructure — k8s, docker, ... —
 * on behalf of the manager) and the user-facing ProvisionMachine RPC.
 *
 * A provisioner authenticates with a dedicated long-lived provisioner token
 * (minted once by CreateProvisioner) and connects out to the manager over
 * ProvisionerStreamService.ProvisionerChannel; the manager never talks to the
 * provisioner's infrastructure directly.
 *
 * ---- Admin management ----
 *
 * @generated from service laelia.v1.ProvisionerService
 */
export declare const ProvisionerService: GenService<{
  /**
   * CreateProvisioner registers a provisioner (title + backend) and mints its
   * one-time long-lived token. The token is returned exactly once and never
   * stored in plaintext.
   *
   * @generated from rpc laelia.v1.ProvisionerService.CreateProvisioner
   */
  createProvisioner: {
    methodKind: "unary";
    input: typeof CreateProvisionerRequestSchema;
    output: typeof CreateProvisionerResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.ProvisionerService.ListProvisioners
   */
  listProvisioners: {
    methodKind: "unary";
    input: typeof ListProvisionersRequestSchema;
    output: typeof ListProvisionersResponseSchema;
  },
  /**
   * @generated from rpc laelia.v1.ProvisionerService.GetProvisioner
   */
  getProvisioner: {
    methodKind: "unary";
    input: typeof GetProvisionerRequestSchema;
    output: typeof ProvisionerSchema;
  },
  /**
   * RotateProvisionerToken bumps the provisioner's token version (killing the
   * old token at its next use) and mints a new one-time token.
   *
   * @generated from rpc laelia.v1.ProvisionerService.RotateProvisionerToken
   */
  rotateProvisionerToken: {
    methodKind: "unary";
    input: typeof RotateProvisionerTokenRequestSchema;
    output: typeof RotateProvisionerTokenResponseSchema;
  },
  /**
   * DeleteProvisioner soft-deletes the provisioner. Refused while any
   * non-deleted machine still references it, so workloads can never silently
   * become unmanaged.
   *
   * @generated from rpc laelia.v1.ProvisionerService.DeleteProvisioner
   */
  deleteProvisioner: {
    methodKind: "unary";
    input: typeof DeleteProvisionerRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * ProvisionMachine creates a machine owned by `owner` (defaults to the
   * caller; only a workspace admin may name another user) and enqueues a
   * provisioning job on the named provisioner. Fully automated: the machine
   * appears and connects without any further user action.
   *
   * @generated from rpc laelia.v1.ProvisionerService.ProvisionMachine
   */
  provisionMachine: {
    methodKind: "unary";
    input: typeof ProvisionMachineRequestSchema;
    output: typeof MachineSchema;
  },
}>;

/**
 * ProvisionerStreamService is the provisioner control channel, mirroring
 * MachineStreamService: jobs flow down, status flows up, over the provisioner's
 * long-lived token. Machines never depend on this stream after they boot — a
 * provisioned machine is a normal machine once its pod is running.
 *
 * @generated from service laelia.v1.ProvisionerStreamService
 */
export declare const ProvisionerStreamService: GenService<{
  /**
   * @generated from rpc laelia.v1.ProvisionerStreamService.ProvisionerChannel
   */
  provisionerChannel: {
    methodKind: "bidi_streaming";
    input: typeof ProvisionerStreamMessageSchema;
    output: typeof ManagerProvisionerStreamMessageSchema;
  },
}>;

