// @generated by protoc-gen-es v2.12.0
// @generated from file v1/setting.proto (package laelia.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../google/api/annotations_pb";
import { file_google_api_field_behavior } from "../google/api/field_behavior_pb";
import { file_store_setting } from "../store/setting_pb";
import { file_v1_annotation } from "./annotation_pb";

/**
 * Describes the file v1/setting.proto.
 */
export const file_v1_setting = /*@__PURE__*/
  fileDesc("ChB2MS9zZXR0aW5nLnByb3RvEglsYWVsaWEudjEiFAoSR2V0UzNDb25maWdSZXF1ZXN0IkQKE0dldFMzQ29uZmlnUmVzcG9uc2USLQoGY29uZmlnGAEgASgLMh0ubGFlbGlhLnN0b3JlLlMzQ29uZmlnU2V0dGluZyJLChVVcGRhdGVTM0NvbmZpZ1JlcXVlc3QSMgoGY29uZmlnGAEgASgLMh0ubGFlbGlhLnN0b3JlLlMzQ29uZmlnU2V0dGluZ0ID4EECIkcKFlVwZGF0ZVMzQ29uZmlnUmVzcG9uc2USLQoGY29uZmlnGAEgASgLMh0ubGFlbGlhLnN0b3JlLlMzQ29uZmlnU2V0dGluZyIXChVHZXRTZXR1cFN0YXR1c1JlcXVlc3QiKwoJU2V0dXBJdGVtEgoKAmlkGAEgASgJEhIKCmNvbmZpZ3VyZWQYAiABKAgiPQoWR2V0U2V0dXBTdGF0dXNSZXNwb25zZRIjCgVpdGVtcxgBIAMoCzIULmxhZWxpYS52MS5TZXR1cEl0ZW0iFwoVR2V0RGVidWdDb25maWdSZXF1ZXN0IikKFkdldERlYnVnQ29uZmlnUmVzcG9uc2USDwoHZW5hYmxlZBgBIAEoCCIwChhVcGRhdGVEZWJ1Z0NvbmZpZ1JlcXVlc3QSFAoHZW5hYmxlZBgBIAEoCEID4EECIiwKGVVwZGF0ZURlYnVnQ29uZmlnUmVzcG9uc2USDwoHZW5hYmxlZBgBIAEoCDLeBQoOU2V0dGluZ1NlcnZpY2USfQoLR2V0UzNDb25maWcSHS5sYWVsaWEudjEuR2V0UzNDb25maWdSZXF1ZXN0Gh4ubGFlbGlhLnYxLkdldFMzQ29uZmlnUmVzcG9uc2UiL4rqMBNsYWVsaWEuc2V0dGluZ3MuZ2V0kOowAYLT5JMCDhIML3YxL3MzQ29uZmlnEpUBCg5VcGRhdGVTM0NvbmZpZxIgLmxhZWxpYS52MS5VcGRhdGVTM0NvbmZpZ1JlcXVlc3QaIS5sYWVsaWEudjEuVXBkYXRlUzNDb25maWdSZXNwb25zZSI+iuowFmxhZWxpYS5zZXR0aW5ncy51cGRhdGWQ6jABmOowAYLT5JMCFjoGY29uZmlnMgwvdjEvczNDb25maWcSiQEKDkdldFNldHVwU3RhdHVzEiAubGFlbGlhLnYxLkdldFNldHVwU3RhdHVzUmVxdWVzdBohLmxhZWxpYS52MS5HZXRTZXR1cFN0YXR1c1Jlc3BvbnNlIjKK6jATbGFlbGlhLnNldHRpbmdzLmdldJDqMAGC0+STAhESDy92MS9zZXR1cFN0YXR1cxKJAQoOR2V0RGVidWdDb25maWcSIC5sYWVsaWEudjEuR2V0RGVidWdDb25maWdSZXF1ZXN0GiEubGFlbGlhLnYxLkdldERlYnVnQ29uZmlnUmVzcG9uc2UiMorqMBNsYWVsaWEuc2V0dGluZ3MuZ2V0kOowAYLT5JMCERIPL3YxL2RlYnVnQ29uZmlnEpwBChFVcGRhdGVEZWJ1Z0NvbmZpZxIjLmxhZWxpYS52MS5VcGRhdGVEZWJ1Z0NvbmZpZ1JlcXVlc3QaJC5sYWVsaWEudjEuVXBkYXRlRGVidWdDb25maWdSZXNwb25zZSI8iuowFmxhZWxpYS5zZXR0aW5ncy51cGRhdGWQ6jABmOowAYLT5JMCFDoBKjIPL3YxL2RlYnVnQ29uZmlnQjFaL2dpdGh1Yi5jb20vUmFueHkvbGFlbGlhL2JhY2tlbmQvZ2VuZXJhdGVkLWdvL3YxYgZwcm90bzM", [file_google_api_annotations, file_google_api_field_behavior, file_store_setting, file_v1_annotation]);

/**
 * Describes the message laelia.v1.GetS3ConfigRequest.
 * Use `create(GetS3ConfigRequestSchema)` to create a new message.
 */
export const GetS3ConfigRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 0);

/**
 * Describes the message laelia.v1.GetS3ConfigResponse.
 * Use `create(GetS3ConfigResponseSchema)` to create a new message.
 */
export const GetS3ConfigResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 1);

/**
 * Describes the message laelia.v1.UpdateS3ConfigRequest.
 * Use `create(UpdateS3ConfigRequestSchema)` to create a new message.
 */
export const UpdateS3ConfigRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 2);

/**
 * Describes the message laelia.v1.UpdateS3ConfigResponse.
 * Use `create(UpdateS3ConfigResponseSchema)` to create a new message.
 */
export const UpdateS3ConfigResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 3);

/**
 * Describes the message laelia.v1.GetSetupStatusRequest.
 * Use `create(GetSetupStatusRequestSchema)` to create a new message.
 */
export const GetSetupStatusRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 4);

/**
 * Describes the message laelia.v1.SetupItem.
 * Use `create(SetupItemSchema)` to create a new message.
 */
export const SetupItemSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 5);

/**
 * Describes the message laelia.v1.GetSetupStatusResponse.
 * Use `create(GetSetupStatusResponseSchema)` to create a new message.
 */
export const GetSetupStatusResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 6);

/**
 * Describes the message laelia.v1.GetDebugConfigRequest.
 * Use `create(GetDebugConfigRequestSchema)` to create a new message.
 */
export const GetDebugConfigRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 7);

/**
 * Describes the message laelia.v1.GetDebugConfigResponse.
 * Use `create(GetDebugConfigResponseSchema)` to create a new message.
 */
export const GetDebugConfigResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 8);

/**
 * Describes the message laelia.v1.UpdateDebugConfigRequest.
 * Use `create(UpdateDebugConfigRequestSchema)` to create a new message.
 */
export const UpdateDebugConfigRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 9);

/**
 * Describes the message laelia.v1.UpdateDebugConfigResponse.
 * Use `create(UpdateDebugConfigResponseSchema)` to create a new message.
 */
export const UpdateDebugConfigResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_setting, 10);

/**
 * SettingService exposes workspace-level configuration. It is admin-only; the
 * handlers enforce workspace admin membership and return
 * connect.CodePermissionDenied otherwise. The S3 secret_key is masked on read;
 * an update carrying a masked secret preserves the stored value.
 *
 * @generated from service laelia.v1.SettingService
 */
export const SettingService = /*@__PURE__*/
  serviceDesc(file_v1_setting, 0);

