// @generated by protoc-gen-es v2.12.0
// @generated from file store/setting.proto (package laelia.store, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Duration } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file store/setting.proto.
 */
export declare const file_store_setting: GenFile;

/**
 * @generated from message laelia.store.WorkspaceProfileSetting
 */
export declare type WorkspaceProfileSetting = Message<"laelia.store.WorkspaceProfileSetting"> & {
  /**
   * The external URL is used for sso authentication callback.
   *
   * @generated from field: string external_url = 1;
   */
  externalUrl: string;

  /**
   * Disallow self-service signup, users can only be invited by the owner.
   *
   * @generated from field: bool disallow_signup = 2;
   */
  disallowSignup: boolean;

  /**
   * Require 2FA for all users.
   *
   * @generated from field: bool require_2fa = 3;
   */
  require2fa: boolean;

  /**
   * The duration for token.
   *
   * @generated from field: google.protobuf.Duration token_duration = 4;
   */
  tokenDuration?: Duration | undefined;

  /**
   * The max duration for role expired.
   *
   * @generated from field: google.protobuf.Duration maximum_role_expiration = 5;
   */
  maximumRoleExpiration?: Duration | undefined;

  /**
   * The workspace domain, e.g. example.com.
   *
   * @generated from field: repeated string domains = 6;
   */
  domains: string[];

  /**
   * Only user and group from the domains can be created and login.
   *
   * @generated from field: bool enforce_identity_domain = 7;
   */
  enforceIdentityDomain: boolean;

  /**
   * Whether to disallow password signin. (Except workspace admins)
   *
   * @generated from field: bool disallow_password_signin = 8;
   */
  disallowPasswordSignin: boolean;

  /**
   * Whether to enable metric collection for the workspace.
   *
   * @generated from field: bool enable_metric_collection = 9;
   */
  enableMetricCollection: boolean;

  /**
   * Whether self-service signup must verify the email address by clicking a
   * link sent to the inbox before the account can sign in. Only takes effect
   * when disallow_signup is false (self-service signup enabled); admin-created
   * users and the first workspace user are always verified. Nil means
   * "disabled" (the default).
   *
   * @generated from field: optional bool require_email_verification = 10;
   */
  requireEmailVerification?: boolean | undefined;
};

/**
 * Describes the message laelia.store.WorkspaceProfileSetting.
 * Use `create(WorkspaceProfileSettingSchema)` to create a new message.
 */
export declare const WorkspaceProfileSettingSchema: GenMessage<WorkspaceProfileSetting>;

/**
 * SMTPSetting holds the outbound SMTP connection details used to send
 * transactional emails (e.g. the signup verification email). When host is
 * empty, the mail service is considered unconfigured.
 *
 * @generated from message laelia.store.SMTPSetting
 */
export declare type SMTPSetting = Message<"laelia.store.SMTPSetting"> & {
  /**
   * SMTP server host, e.g. "smtp.example.com". Empty means not configured.
   *
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * SMTP server port, e.g. 587 (STARTTLS) or 465 (implicit TLS).
   *
   * @generated from field: int32 port = 2;
   */
  port: number;

  /**
   * Optional username for AUTH PLAIN. Empty means no authentication.
   *
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * Password for AUTH PLAIN. Masked on read-back.
   *
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * The From address shown in sent mail.
   *
   * @generated from field: string from = 5;
   */
  from: string;

  /**
   * use_tls enables TLS: port 465 uses implicit TLS, other ports use STARTTLS
   * after connecting. When false, the connection is plaintext.
   *
   * @generated from field: bool use_tls = 6;
   */
  useTls: boolean;
};

/**
 * Describes the message laelia.store.SMTPSetting.
 * Use `create(SMTPSettingSchema)` to create a new message.
 */
export declare const SMTPSettingSchema: GenMessage<SMTPSetting>;

/**
 * @generated from message laelia.store.PasswordRestrictionSetting
 */
export declare type PasswordRestrictionSetting = Message<"laelia.store.PasswordRestrictionSetting"> & {
  /**
   * min_length is the minimum length for password, should no less than 8.
   *
   * @generated from field: int32 min_length = 1;
   */
  minLength: number;

  /**
   * require_number requires the password must contains at least one number.
   *
   * @generated from field: bool require_number = 2;
   */
  requireNumber: boolean;

  /**
   * require_letter requires the password must contains at least one letter, regardless of upper case or lower case
   *
   * @generated from field: bool require_letter = 3;
   */
  requireLetter: boolean;

  /**
   * require_uppercase_letter requires the password must contains at least one upper case letter.
   *
   * @generated from field: bool require_uppercase_letter = 4;
   */
  requireUppercaseLetter: boolean;

  /**
   * require_uppercase_letter requires the password must contains at least one special character.
   *
   * @generated from field: bool require_special_character = 5;
   */
  requireSpecialCharacter: boolean;

  /**
   * require_reset_password_for_first_login requires users to reset their password after the 1st login.
   *
   * @generated from field: bool require_reset_password_for_first_login = 6;
   */
  requireResetPasswordForFirstLogin: boolean;

  /**
   * password_rotation requires users to reset their password after the duration.
   *
   * @generated from field: google.protobuf.Duration password_rotation = 7;
   */
  passwordRotation?: Duration | undefined;
};

/**
 * Describes the message laelia.store.PasswordRestrictionSetting.
 * Use `create(PasswordRestrictionSettingSchema)` to create a new message.
 */
export declare const PasswordRestrictionSettingSchema: GenMessage<PasswordRestrictionSetting>;

/**
 * S3ConfigSetting holds the connection details for the object storage used to
 * back file upload/download. When endpoint and bucket are both empty, S3 is
 * considered unconfigured and upload/download endpoints reject with
 * "s3 not configured".
 *
 * @generated from message laelia.store.S3ConfigSetting
 */
export declare type S3ConfigSetting = Message<"laelia.store.S3ConfigSetting"> & {
  /**
   * S3-compatible endpoint URL, e.g. "https://s3.amazonaws.com" or a MinIO
   * endpoint. Empty for AWS defaults.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;

  /**
   * AWS region, e.g. "us-east-1".
   *
   * @generated from field: string region = 2;
   */
  region: string;

  /**
   * Bucket name.
   *
   * @generated from field: string bucket = 3;
   */
  bucket: string;

  /**
   * Static access key id.
   *
   * @generated from field: string access_key = 4;
   */
  accessKey: string;

  /**
   * Static secret access key. Stored as plaintext in the setting row (same
   * mechanism as AUTH_SECRET); masked on read.
   *
   * @generated from field: string secret_key = 5;
   */
  secretKey: string;

  /**
   * Use path-style addressing (required for MinIO and many S3-compatible
   * stores; false for AWS virtual-host style).
   *
   * @generated from field: bool force_path_style = 6;
   */
  forcePathStyle: boolean;

  /**
   * Whether the endpoint uses TLS. Only meaningful when endpoint is set.
   *
   * @generated from field: bool use_ssl = 7;
   */
  useSsl: boolean;
};

/**
 * Describes the message laelia.store.S3ConfigSetting.
 * Use `create(S3ConfigSettingSchema)` to create a new message.
 */
export declare const S3ConfigSettingSchema: GenMessage<S3ConfigSetting>;

/**
 * LlmAgentConfigSetting is the workspace-level LLM agent configuration. The
 * only knob today is whether users may self-provide an inline api_provider /
 * api_key / model when creating or editing a builtin-pi agent, in addition to
 * using the managed global API providers. Defaults to enabled when unset.
 *
 * @generated from message laelia.store.LlmAgentConfigSetting
 */
export declare type LlmAgentConfigSetting = Message<"laelia.store.LlmAgentConfigSetting"> & {
  /**
   * allow_user_self_provided_keys gates the legacy inline api_provider/api_key
   * path on builtin-pi agents. When true, any user who may create/edit the
   * agent can fill in their own LLM API key; when false, only a caller holding
   * agents.edit (workspace admin) may, and everyone else must use a global
   * provider. Default true.
   *
   * @generated from field: bool allow_user_self_provided_keys = 1;
   */
  allowUserSelfProvidedKeys: boolean;
};

/**
 * Describes the message laelia.store.LlmAgentConfigSetting.
 * Use `create(LlmAgentConfigSettingSchema)` to create a new message.
 */
export declare const LlmAgentConfigSettingSchema: GenMessage<LlmAgentConfigSetting>;

/**
 * UserMcpConfigSetting is the workspace-level personal MCP configuration:
 * whether users may configure their own personal MCP servers and enable them
 * on their own agents, plus the optional target IP allow/deny policy that
 * bounds where those servers (or all MCP servers) may connect.
 *
 * @generated from message laelia.store.UserMcpConfigSetting
 */
export declare type UserMcpConfigSetting = Message<"laelia.store.UserMcpConfigSetting"> & {
  /**
   * allow_user_mcp_servers gates personal MCP servers: when true, any user may
   * create/edit/delete their own servers and enable them on their agents;
   * when false, personal servers are hidden from agent catalogs and creation
   * is rejected (existing rows are retained and restored on re-enable).
   *
   * @generated from field: bool allow_user_mcp_servers = 1;
   */
  allowUserMcpServers: boolean;

  /**
   * mcp_ip_policy controls the MCP target IP allow/deny policy. Zero value
   * (enabled=false) means no restriction, preserving existing behavior for
   * stored rows that predate this field.
   *
   * @generated from field: laelia.store.McpIpPolicy mcp_ip_policy = 2;
   */
  mcpIpPolicy?: McpIpPolicy | undefined;
};

/**
 * Describes the message laelia.store.UserMcpConfigSetting.
 * Use `create(UserMcpConfigSettingSchema)` to create a new message.
 */
export declare const UserMcpConfigSettingSchema: GenMessage<UserMcpConfigSetting>;

/**
 * McpIpPolicy is the workspace MCP target IP allow/deny policy, guarding
 * against SSRF (internal network / cloud metadata) via user-configured MCP
 * server URLs.
 *
 * @generated from message laelia.store.McpIpPolicy
 */
export declare type McpIpPolicy = Message<"laelia.store.McpIpPolicy"> & {
  /**
   * enabled turns the policy on. When false, no restriction is enforced and
   * existing behavior is unchanged. Defaults to disabled.
   *
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * scope selects the servers the policy applies to.
   *
   * @generated from field: laelia.store.McpIpPolicy.Scope scope = 2;
   */
  scope: McpIpPolicy_Scope;

  /**
   * allow_cidrs is the allow list: when non-empty the target IP must match one
   * of these CIDR prefixes; when empty, the allow side does not restrict.
   *
   * @generated from field: repeated string allow_cidrs = 3;
   */
  allowCidrs: string[];

  /**
   * deny_cidrs is the deny list: a target IP matching any of these CIDR
   * prefixes is rejected, taking precedence over the allow list.
   *
   * @generated from field: repeated string deny_cidrs = 4;
   */
  denyCidrs: string[];
};

/**
 * Describes the message laelia.store.McpIpPolicy.
 * Use `create(McpIpPolicySchema)` to create a new message.
 */
export declare const McpIpPolicySchema: GenMessage<McpIpPolicy>;

/**
 * Scope selects which MCP servers the policy applies to.
 *
 * @generated from enum laelia.store.McpIpPolicy.Scope
 */
export enum McpIpPolicy_Scope {
  /**
   * Unspecified is treated as SCOPE_USER_CREATED (conservative default).
   *
   * @generated from enum value: SCOPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Applies to every MCP server, including admin-maintained workspace ones.
   *
   * @generated from enum value: SCOPE_ALL = 1;
   */
  ALL = 1,

  /**
   * Applies only to personal-scope servers (owner_id != 0).
   *
   * @generated from enum value: SCOPE_USER_CREATED = 2;
   */
  USER_CREATED = 2,
}

/**
 * Describes the enum laelia.store.McpIpPolicy.Scope.
 */
export declare const McpIpPolicy_ScopeSchema: GenEnum<McpIpPolicy_Scope>;

