// @generated by protoc-gen-es v2.12.0
// @generated from file store/setting.proto (package laelia.store, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file store/setting.proto.
 */
export const file_store_setting = /*@__PURE__*/
  fileDesc("ChNzdG9yZS9zZXR0aW5nLnByb3RvEgxsYWVsaWEuc3RvcmUilgEKD1MzQ29uZmlnU2V0dGluZxIQCghlbmRwb2ludBgBIAEoCRIOCgZyZWdpb24YAiABKAkSDgoGYnVja2V0GAMgASgJEhIKCmFjY2Vzc19rZXkYBCABKAkSEgoKc2VjcmV0X2tleRgFIAEoCRIYChBmb3JjZV9wYXRoX3N0eWxlGAYgASgIEg8KB3VzZV9zc2wYByABKAhCNFoyZ2l0aHViLmNvbS9SYW54eS9sYWVsaWEvYmFja2VuZC9nZW5lcmF0ZWQtZ28vc3RvcmViBnByb3RvMw");

/**
 * Describes the message laelia.store.S3ConfigSetting.
 * Use `create(S3ConfigSettingSchema)` to create a new message.
 */
export const S3ConfigSettingSchema = /*@__PURE__*/
  messageDesc(file_store_setting, 0);

