apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provisioner.labels" . | nindent 4 }}
